import {BELTS,RANK_XP,rank,COSMETICS,ACHIEVEMENTS,CHAPTERS,UPGRADE_COSTS,STORY_XP,ENVIRONMENTS,fmtTime} from './data.js';
import {SaveStore} from './save.js';
import {Runner,STEP} from './engine.js';
import {Renderer} from './render.js';
import {AudioBus} from './audio.js';
const $=id=>document.getElementById(id),panel=$('panel');
let storage;try{storage=window.localStorage}catch{storage={getItem(){throw Error('Unavailable')},setItem(){throw Error('Unavailable')}}}
const store=new SaveStore(storage);let save=store.data;const renderer=new Renderer($('game'));const audio=new AudioBus(save.settings);
let game=null,mode='home',page='',chapter=null,paused=false,promotionTime=0,promotionQueue=[],last=0,accumulator=0,saveClock=0,bannerTimer=0,toastTimer=0,resultTimer=0,finished=false,runStartXP=0,runStartCoins=0,previousBest=0,resumeTime=0,bestCrossed=false,hudClock=0;
let credited={xp:0,coins:0,medals:0,distance:0,time:0,roll:0,double:0,precision:0};
const number=n=>Math.floor(n).toLocaleString();
function swatch(r){return `<span class="belt-swatch" style="--belt:${r.color}"><b>${'<i></i>'.repeat(r.stripes)}</b></span>`;}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;toastTimer=3.5;}
function persist(){store.data=save;const ok=store.save();save=store.data;audio.settings=save.settings;$('save-status').textContent=ok?'PROGRESS SAVED ON THIS DEVICE':'SAVE UNAVAILABLE — EXPORT YOUR SAVE IN SETTINGS';if(!ok&&!persist.warned){toast('Storage unavailable. Keep this tab open and export your save in Settings.');persist.warned=true;}return ok;}
if(save.active){save.active=null;persist();}
function updateHome(){const r=rank(save.xp),pct=r.next?(save.xp-r.floor)/(r.next-r.floor)*100:100;$('wallet').textContent=number(save.coins)+' COINS';$('home-belt').innerHTML=swatch(r)+r.name.toUpperCase()+' / '+r.stripes+' STRIPES';$('next-rank').textContent=r.next?number(r.next-save.xp)+' XP TO '+((r.level+1)%5===0?'PROMOTION':'NEXT STRIPE'):'BLACK BELT · KEEP YOUR FLOW';$('home-xp').style.width=pct+'%';$('home-record').textContent=save.stats.bestDistance>0?'BEST '+number(save.stats.bestDistance)+' m / '+fmtTime(save.stats.bestTime):'A fresh start on the mats.';$('sound').textContent=save.settings.sound?'SOUND ON':'SOUND OFF';$('sound').setAttribute('aria-pressed',String(save.settings.sound));}
function awardXP(amount,celebrate=true){const old=rank(save.xp);save.xp+=Math.max(0,Math.floor(amount));const next=rank(save.xp);if(next.level>old.level&&celebrate){promotionQueue.push(next);if(next.level>=2&&old.level<2)toast('Story Mode unlocked — find it in the dojo menu.');}return next;}
function syncUnlocks(){for(const item of COSMETICS)if(item.unlock&&save.achievements.includes(item.unlock)&&!save.unlocks.includes(item.id))save.unlocks.push(item.id);}
function achievementValue(a){if(a.stat==='rank')return rank(save.xp).level;if(a.stat==='environmentCount')return save.stats.environments.length;if(a.stat==='upgradeLevels')return save.upgrades.jump+save.upgrades.luck;return save.stats[a.stat]||0;}
function achievements(){for(const a of ACHIEVEMENTS){if(!save.achievements.includes(a.id)&&achievementValue(a)>=a.target){save.achievements.push(a.id);save.coins+=a.coins;awardXP(a.xp);toast('ACHIEVEMENT: '+a.name+' · +'+a.coins+' coins');}}syncUnlocks();}
function bank(){if(!game||finished)return;const xp=Math.floor(game.xp);awardXP(xp-credited.xp);save.coins+=game.coins-credited.coins;save.stats.coins+=game.coins-credited.coins;save.stats.medals+=game.medals-credited.medals;save.stats.totalDistance+=game.distance-credited.distance;save.stats.playtime+=game.time-credited.time;save.stats.rollClears+=game.rollClears-credited.roll;save.stats.doubleJumps+=game.doubleJumps-credited.double;save.stats.precision+=game.precision-credited.precision;save.stats.bestDistance=Math.max(save.stats.bestDistance,game.distance);save.stats.bestTime=Math.max(save.stats.bestTime,game.time);save.stats.bestClean=Math.max(save.stats.bestClean,game.clean);save.stats.highestSpeed=Math.max(save.stats.highestSpeed,game.speed);if(!save.stats.environments.includes(game.environment))save.stats.environments.push(game.environment);credited={xp,coins:game.coins,medals:game.medals,distance:game.distance,time:game.time,roll:game.rollClears,double:game.doubleJumps,precision:game.precision};save.active={id:save.active?.id||String(Date.now()),time:game.time,distance:game.distance};achievements();persist();updateHome();}
function banner(title,sub='',duration=2.4){$('banner').innerHTML='';const a=document.createElement('span');a.textContent=title;$('banner').append(a);if(sub){const b=document.createElement('small');b.textContent=sub;$('banner').append(b);}$('banner').hidden=false;bannerTimer=duration;}
function start(selected=null){if(selected&&save.xp<STORY_XP)return;if(selected){const i=CHAPTERS.indexOf(selected);if(i>0&&!save.story.completed.includes(CHAPTERS[i-1].id))return;}audio.activate();panel.close();chapter=selected;game=new Runner({jump:save.upgrades.jump,luck:save.upgrades.luck,chapter});renderer.lastEnvironment=game.environment;renderer.transition=1;renderer.particles=[];renderer.labels=[];mode='run';finished=false;paused=false;promotionTime=0;resumeTime=0;bestCrossed=false;promotionQueue=[];resultTimer=0;accumulator=0;runStartXP=save.xp;runStartCoins=save.coins;previousBest=save.stats.bestDistance;game.targetBest=previousBest>=50?previousBest:0;credited={xp:0,coins:0,medals:0,distance:0,time:0,roll:0,double:0,precision:0};save.stats.attempts++;save.active={id:String(Date.now()),time:0,distance:0};persist();document.documentElement.classList.add('playing');for(const id of ['home','results','pause-overlay','promotion'])$(id).hidden=true;for(const id of ['hud','run-controls','pause'])$(id).hidden=false;$('pause').textContent='PAUSE';renderer.resize();banner(chapter?chapter.name:'FIRST LIGHT DOJO','JUMP over equipment · hold ROLL underneath',3.8);$('game').focus({preventScroll:true});updateHUD();}
function pause(){if(mode!=='run'||finished)return;paused=!paused;game.p.rollHeld=false;game.p.shrimp=false;if(paused)bank();$('pause-overlay').hidden=!paused;$('pause').textContent=paused?'RESUME':'PAUSE';accumulator=0;if(paused)$('resume').focus({preventScroll:true});else{resumeTime=.8;banner('READY','Back to your rhythm',.8);$('game').focus({preventScroll:true});}}
function finish(quit=false){if(finished||!game)return;bank();save.stats.runs++;if(game.dead)save.stats.deaths++;let reward='';if(game.complete&&chapter&&!save.story.completed.includes(chapter.id)){save.story.completed.push(chapter.id);save.coins+=chapter.reward;awardXP(chapter.xp,false);reward=`Chapter reward: +${chapter.reward} coins / +${chapter.xp} XP`;}if(game.distance>previousBest&&previousBest>0&&game.distance>100){awardXP(25,false);reward+=(reward?' · ':'')+'Personal best +25 XP';}save.active=null;achievements();finished=true;persist();mode='results';paused=false;promotionQueue=[];promotionTime=0;$('promotion').hidden=true;$('pause-overlay').hidden=true;$('pause').hidden=true;$('banner').hidden=true;const r=rank(save.xp);$('results').innerHTML=`<div class="result-card"><div class="eyebrow">${game.complete?'CHAPTER COMPLETE':game.distance>previousBest&&game.distance>0?'NEW PERSONAL BEST':quit?'ROUND SAVED':'BACK TO THE MATS'}</div><h2>${game.complete?'ROUND COMPLETE.':'ONE MORE ROUND?'}</h2><p class="result-reason">${quit?'Your progress is banked. Pick up another round anytime.':game.complete?'You made it to the end of this chapter.':game.reason}</p><div class="result-grid"><div><strong>${number(game.distance)} m</strong><small>DISTANCE</small></div><div><strong>${fmtTime(game.time)}</strong><small>SURVIVED</small></div><div><strong>+${number(save.xp-runStartXP)}</strong><small>XP EARNED</small></div><div><strong>+${number(save.coins-runStartCoins)}</strong><small>COINS + BONUSES</small></div><div><strong>${game.medals}</strong><small>MEDALS</small></div><div><strong>${game.clean}</strong><small>CLEAN CLEARS</small></div></div><div class="result-progress">${swatch(r)}${r.name.toUpperCase()} / ${r.stripes} STRIPES${r.next?' · '+number(r.next-save.xp)+' XP TO NEXT':''}</div><div class="meter"><i style="width:${r.next?(save.xp-r.floor)/(r.next-r.floor)*100:100}%"></i></div>${reward?'<p class="help">'+reward+'</p>':''}<p class="help">${game.precision} tight clearances · ${nextGoal()}</p><div class="actions"><button class="primary" id="again">RUN AGAIN</button><button id="return-home">DOJO MENU</button></div></div>`;$('results').hidden=false;$('again').onclick=()=>start(chapter);$('return-home').onclick=home;$('again').focus({preventScroll:true});updateHome();}
function home(){mode='home';paused=false;game=null;promotionQueue=[];document.documentElement.classList.remove('playing');for(const id of ['results','hud','run-controls','pause','pause-overlay','banner','promotion'])$(id).hidden=true;$('home').hidden=false;updateHome();renderer.resize();$('play').focus({preventScroll:true});}
function updateHUD(){if(!game)return;const r=rank(save.xp);$('distance').textContent=number(game.distance)+' m';$('time').textContent=fmtTime(game.time);$('run-rank').textContent=r.name.toUpperCase()+' / '+r.stripes+' STRIPES';$('run-xp').style.width=(r.next?(save.xp-r.floor)/(r.next-r.floor)*100:100)+'%';$('run-loot').textContent=game.coins+' C · '+game.medals+' M';if(game.targetBest>0&&game.distance>=game.targetBest)$('distance').classList.add('record');else $('distance').classList.remove('record');$('effect').textContent=Object.entries(game.effects).filter(([,n])=>n>0).map(([k,n])=>(k==='focus'?'2× XP':'MAGNET')+' '+Math.ceil(n)+'s').join(' / ')||(game.clean>=10?'FLOW / '+game.clean+' CLEARS':'');$('run-location').textContent=ENVIRONMENTS[game.environment].name.toUpperCase()+(chapter?' · '+Math.max(0,Math.ceil(chapter.duration-game.time))+'s TO FINISH':game.environment<5?' · NEXT AREA '+Math.ceil(60-game.time%60)+'s':' · CHAMPIONSHIP PACE');}
function showPromotion(){if(promotionTime>0||!promotionQueue.length||mode!=='run'||game.dead)return;const r=promotionQueue.shift();promotionTime=1.45;$('promotion').innerHTML='<span>'+swatch(r)+'</span><span>'+r.name.toUpperCase()+' BELT</span><strong>'+(r.stripes?'STRIPE '+r.stripes+' EARNED':'PROMOTED')+'</strong><span>Your work stays with you.</span>';$('promotion').hidden=false;audio.sfx('promotion');}
const pageNames={customize:'THE LOCKER',upgrades:'PUT IN THE REPS',progress:'EARN YOUR STRIPES',achievements:'MILESTONES',stats:'YOUR MAT TIME',story:'THE JOURNEY',settings:'SETTINGS'};
function openPage(name){page=name;$('panel-title').textContent=pageNames[name];renderPage();if(!panel.open)panel.showModal();}
function renderPage(){updateHome();const r=rank(save.xp);let html='';
if(page==='customize'){html=`<div class="locker-top"><canvas id="character-preview" width="160" height="160" aria-label="Equipped character preview"></canvas><div><h3>YOUR GI. YOUR RUN.</h3><p>${r.name} belt · ${r.stripes} stripes</p><p>${number(save.coins)} coins available</p><p>Belts follow your earned rank.</p></div></div>`;for(const category of ['gi','hair','rash','patch','wrist']){html+='<h3 class="category">'+({gi:'GI',hair:'HAIR',rash:'RASHGUARD',patch:'PATCHES',wrist:'WRIST TAPE'}[category])+'</h3><div class="cosmetics">';for(const c of COSMETICS.filter(c=>c.category===category)){const owned=save.unlocks.includes(c.id),equipped=save.equipped[category]===c.id;html+=`<button class="cosmetic ${equipped?'selected':''}" data-cosmetic="${c.id}" ${!owned&&c.unlock?'disabled':''} aria-pressed="${equipped}"><span class="chip" style="background:${c.color}"></span>${c.name}<small>${equipped?'EQUIPPED':owned?'EQUIP':c.unlock?c.hint:c.cost+' COINS'}</small></button>`;}html+='</div>';}}
if(page==='upgrades'){html='<p>Small advantages earned on the mats. Your timing still matters.</p><div class="cards">';for(const k of ['jump','luck']){const lv=save.upgrades[k];html+=`<article class="card"><div class="eyebrow">LEVEL ${lv} / 4</div><h3>${k==='jump'?'JUMP / EXPLOSIVENESS':'LUCK / OPPORTUNITY'}</h3><p>${k==='jump'?'Each level adds a little lift to both jumps. Maximum +7% launch power.':'Each level improves the chance of bonus medals and temporary power-ups. No random saves from danger.'}</p><div class="meter"><i style="width:${lv/4*100}%"></i></div><button data-upgrade="${k}" ${lv>=4||save.coins<UPGRADE_COSTS[lv]?'disabled':''}>${lv>=4?'FULLY TRAINED':'TRAIN · '+UPGRADE_COSTS[lv]+' COINS'}</button></article>`;}html+='</div><p class="help">Your training and purchases are permanent.</p>';}
if(page==='progress'){html=`<p>${number(save.xp)} lifetime XP. Four stripes per belt, then promotion. Progress is earned across every run.</p>`;for(let b=0;b<5;b++){const rr={color:BELTS[b][1],stripes:b<r.belt?4:b===r.belt?r.stripes:0};html+=`<div class="rank-row"><div>${swatch(rr)}${BELTS[b][0].toUpperCase()}</div><small>${b<r.belt?'COMPLETED':b===r.belt?(b===4?'FINAL BELT':r.stripes+' / 4 STRIPES'):number(RANK_XP[b*5])+' XP'}</small></div>`;}html+='<p>Distance, medals, clean clears, new environments, achievements, and chapter completions earn XP. A promotion pauses the course briefly so you can enjoy the moment.</p>';}
if(page==='achievements'){html=`<p>${save.achievements.length} / ${ACHIEVEMENTS.length} milestones earned. Rewards are granted automatically.</p><div class="cards">`;for(const a of ACHIEVEMENTS){const won=save.achievements.includes(a.id),v=Math.min(a.target,achievementValue(a));html+=`<article class="card ${won?'earned':''}"><div class="eyebrow">${won?'EARNED':Math.floor(v)+' / '+a.target}</div><h3>${a.name}</h3><p>${a.description}</p><div class="meter"><i style="width:${v/a.target*100}%"></i></div><p class="meta">+${a.coins} coins / +${a.xp} XP</p></article>`;}html+='</div>';}
if(page==='stats'){const s=save.stats;const pairs=[['Runs completed',number(s.runs)],['Runs started',number(s.attempts)],['Deaths',number(s.deaths)],['Total distance',number(s.totalDistance)+' m'],['Personal best',number(s.bestDistance)+' m'],['Longest run',fmtTime(s.bestTime)],['Mat time',fmtTime(s.playtime)],['Coins collected',number(s.coins)],['Medals',number(s.medals)],['Best clean sequence',number(s.bestClean)],['Roll clears',number(s.rollClears)],['Double jumps',number(s.doubleJumps)],['Tight clearances',number(s.precision)],['Environments',s.environments.length+' / 6'],['Highest pace',(s.highestSpeed/10).toFixed(1)+' m/s'],['Lifetime XP',number(save.xp)],['Current rank',r.name+' / '+r.stripes]];if(s.legacyBest)pairs.push(['Original game score',number(s.legacyBest)]);html='<div class="stats-grid">'+pairs.map(([k,v])=>`<div class="stat"><strong>${v}</strong><span>${k}</span></div>`).join('')+'</div>';}
if(page==='story'){html=`<p>Four short chapters through the jiu-jitsu world. Complete each round to open the next. Endless remains your main training ground.</p>${save.xp<STORY_XP?'<div class="notice">Unlocks at WHITE BELT / 2 STRIPES. '+number(STORY_XP-save.xp)+' XP to go.</div>':''}<div class="cards">`;CHAPTERS.forEach((c,i)=>{const done=save.story.completed.includes(c.id),unlocked=save.xp>=STORY_XP&&(i===0||save.story.completed.includes(CHAPTERS[i-1].id));html+=`<article class="card ${done?'earned':unlocked?'':'locked'}"><div class="eyebrow">CHAPTER 0${i+1} / ${fmtTime(c.duration)}</div><h3>${c.name}</h3><p>${c.text}</p><div class="meta">${done?'COMPLETED · REPLAY ANYTIME':c.reward+' COINS / '+c.xp+' XP ON FIRST CLEAR'}</div><button data-chapter="${i}" ${unlocked?'':'disabled'}>${done?'REPLAY CHAPTER':unlocked?'START CHAPTER':'LOCKED'}</button></article>`;});html+='</div>';}
if(page==='settings'){html=`<label class="setting">Game audio (master)<input type="checkbox" data-setting="sound" ${save.settings.sound?'checked':''}></label><label class="setting">Music<input type="checkbox" data-setting="music" ${save.settings.music?'checked':''}></label><label class="setting">Volume<input aria-label="Volume" type="range" min="0" max="1" step=".05" value="${save.settings.volume}" data-setting="volume"></label><label class="setting">Reduced motion & flashes<input type="checkbox" data-setting="reducedMotion" ${save.settings.reducedMotion?'checked':''}></label><label class="setting">First-time obstacle tips<input type="checkbox" data-setting="hints" ${save.settings.hints?'checked':''}></label><h3>YOUR SAVE</h3><p>Progress saves automatically in this browser. Use export and import to move it to another device or keep a backup. Clearing browser data removes local saves.</p><div class="actions"><button id="export">EXPORT SAVE</button><button id="import">IMPORT SAVE</button></div><p class="help">Import replaces this device's progress. Export first if you want to keep it.</p><h3>CONTROLS</h3><p>W / ↑ / Space: jump, then press again for double jump.<br>S / ↓ / D / →: roll. Hold to stay low.<br>A / ←: shrimp backward while staying low.<br>P / Escape: pause. R: retry after a run.<br>On touch screens: use the two large buttons. Tap the course to jump.</p><p>Gold coins: +1 coin. Medals: +5 coins and bonus XP.<br>M: 8-second magnet. 2: 8-second double XP.<br>All dangerous collisions end your run instantly.</p>`;}
$('panel-body').innerHTML=html;if(page==='customize')renderer.preview($('character-preview'),save);
for(const b of panel.querySelectorAll('[data-cosmetic]'))b.onclick=()=>{const c=COSMETICS.find(x=>x.id===b.dataset.cosmetic);if(!save.unlocks.includes(c.id)){if(c.unlock)return;if(save.coins<c.cost){toast('Keep running — you need '+(c.cost-save.coins)+' more coins.');return;}save.coins-=c.cost;save.unlocks.push(c.id);}save.equipped[c.category]=c.id;persist();audio.sfx('click');renderPage();};
for(const b of panel.querySelectorAll('[data-upgrade]'))b.onclick=()=>{const k=b.dataset.upgrade,lv=save.upgrades[k];if(lv>=4||save.coins<UPGRADE_COSTS[lv])return;save.coins-=UPGRADE_COSTS[lv];save.upgrades[k]++;achievements();persist();audio.sfx('promotion');renderPage();};
for(const b of panel.querySelectorAll('[data-chapter]'))b.onclick=()=>start(CHAPTERS[Number(b.dataset.chapter)]);
for(const input of panel.querySelectorAll('[data-setting]'))input.oninput=()=>{save.settings[input.dataset.setting]=input.type==='checkbox'?input.checked:Number(input.value);audio.settings=save.settings;audio.activate();persist();updateHome();};
if(page==='settings'){$('export').onclick=()=>{const url=URL.createObjectURL(new Blob([store.export()],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='medal-run-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('import').onclick=()=>$('import-save').click();}
}
$('import-save').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.size>1024*1024){toast('This save file is too large.');e.target.value='';return;}try{const data=await f.text();if(!window.confirm('Replace this device’s Medal Run progress with this save?'))return;const ok=store.import(data);save=store.data;audio.settings=save.settings;syncUnlocks();updateHome();renderPage();toast(ok?'Save imported. Welcome back.':'Imported in memory. Storage is unavailable; export a backup.');}catch(err){toast(err.message);}finally{e.target.value='';}};
$('play').onclick=()=>start();$('pause').onclick=pause;$('resume').onclick=pause;$('quit').onclick=()=>finish(true);$('close-panel').onclick=()=>panel.close();panel.addEventListener('click',e=>{if(e.target===panel){const r=panel.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)panel.close();}});for(const b of document.querySelectorAll('[data-page]'))b.onclick=()=>{audio.activate();openPage(b.dataset.page);};$('sound').onclick=()=>{save.settings.sound=!save.settings.sound;audio.settings=save.settings;audio.activate();persist();updateHome();};
function act(name,held=true){if(mode!=='run'||paused||finished)return;audio.activate();game.action(name,held);}
for(const [id,name] of [['jump','jump'],['roll','roll']]){const b=$(id);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);act(name);});const release=e=>{e.preventDefault();if(game&&name==='roll')game.action('roll',false);};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);}
const touchGesture={id:null,x:0,y:0};
$('game').addEventListener('pointerdown',e=>{if(mode!=='run')return;e.preventDefault();touchGesture.id=e.pointerId;touchGesture.x=e.clientX;touchGesture.y=e.clientY;$('game').setPointerCapture?.(e.pointerId);});
$('game').addEventListener('pointerup',e=>{if(mode!=='run'||touchGesture.id!==e.pointerId)return;e.preventDefault();const dx=e.clientX-touchGesture.x,dy=e.clientY-touchGesture.y;touchGesture.id=null;if(Math.max(Math.abs(dx),Math.abs(dy))<24){act('jump');return;}if(Math.abs(dx)>Math.abs(dy)&&dx<-28){act('shrimp');setTimeout(()=>{if(game)game.action('shrimp',false);},260);return;}if(Math.abs(dy)>Math.abs(dx)&&dy>28){act('roll');setTimeout(()=>{if(game)game.action('roll',false);},360);return;}if(Math.abs(dy)>Math.abs(dx)&&dy<-28){act('jump');}});
$('game').addEventListener('pointercancel',e=>{if(touchGesture.id===e.pointerId)touchGesture.id=null;});
const jumpKeys=['Space','KeyW','ArrowUp'],rollKeys=['KeyS','ArrowDown','KeyD','ArrowRight'],shrimpKeys=['KeyA','ArrowLeft'];const held=new Set();
window.addEventListener('keydown',e=>{if(panel.open)return;if(mode==='results'&&!e.repeat&&(e.code==='KeyR'||(['Space','Enter'].includes(e.code)&&e.target.tagName!=='BUTTON'))){e.preventDefault();start(chapter);return;}if(mode!=='run')return;if([...jumpKeys,...rollKeys,...shrimpKeys,'KeyP','Escape'].includes(e.code))e.preventDefault();if(e.repeat||held.has(e.code))return;held.add(e.code);if(['KeyP','Escape'].includes(e.code)){pause();return;}if(jumpKeys.includes(e.code))act('jump');if(rollKeys.includes(e.code))act('roll');if(shrimpKeys.includes(e.code))act('shrimp');});
window.addEventListener('keyup',e=>{held.delete(e.code);if(game&&[...rollKeys,...shrimpKeys].includes(e.code)){game.p.rollHeld=[...held].some(k=>rollKeys.includes(k)||shrimpKeys.includes(k));game.p.shrimp=[...held].some(k=>shrimpKeys.includes(k));}});
function suspend(){held.clear();if(mode==='run'&&!finished){if(!paused)pause();else bank();}else persist();}document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend();});window.addEventListener('pagehide',suspend);window.addEventListener('blur',()=>{if(mode==='run'&&!paused)suspend();});window.addEventListener('resize',()=>renderer.resize());
window.addEventListener('storage',e=>{if(e.key==='medal-run-save'&&e.newValue){save=store.load();store.data=save;audio.settings=save.settings;finished=true;home();toast('Progress synced from another tab. Play in one tab at a time.');}});
function nextGoal(){const a=ACHIEVEMENTS.filter(a=>!save.achievements.includes(a.id)).sort((a,b)=>achievementValue(b)/b.target-achievementValue(a)/a.target)[0];return a?'Next: '+a.name+' ('+Math.min(a.target,Math.floor(achievementValue(a)))+'/'+a.target+')':'All milestones earned.';}
function coach(){if(!game||!save.settings.hints||bannerTimer>0||game.dead)return;const px=game.world+game.p.x;const obstacle=[...game.objects.filter(o=>o.kind==='obstacle'),...game.terrain.filter(t=>t.type==='gap')].filter(o=>o.x>px+game.speed*1.1&&o.x<game.world+455).sort((a,b)=>a.x-b.x)[0];if(!obstacle)return;const kind=obstacle.overhead?'roll':obstacle.type==='gap'?'gap':obstacle.type==='podium'?'high':['bench','mats'].includes(obstacle.type)?'wide':'jump';if(save.seenHints.includes(kind))return;const tips={jump:['FIND YOUR TIMING','Tap JUMP before the equipment. Tap again for extra height.'],roll:['STAY LOW','Hold ROLL until you are completely under the table.'],gap:['WATCH THE EDGE','Jump across the gap. Save the second jump if needed.'],high:['DOUBLE JUMP','Jump early, then tap again to get above the podium.'],wide:['CLEAR THE WHOLE OBSTACLE','Use a second jump to stay above wider equipment.']};save.seenHints.push(kind);persist();banner(...tips[kind],3);}
function frame(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('toast').hidden=true;}if(bannerTimer>0&&!paused){bannerTimer-=dt;if(bannerTimer<=0)$('banner').hidden=true;}if(mode==='run'&&!paused&&!finished){if(resumeTime>0){resumeTime-=dt;accumulator=0;}else if(promotionTime>0){promotionTime-=dt;accumulator=0;if(promotionTime<=0){$('promotion').hidden=true;}}else{accumulator+=dt;while(accumulator>=STEP&&!game.dead&&!game.complete){game.step(STEP);accumulator-=STEP;}for(const event of game.drain()){renderer.event(event,game,save.settings.reducedMotion);audio.sfx(event.type==='pickup'?event.item:event.type);if(event.type==='environment')banner(ENVIRONMENTS[event.index].name,ENVIRONMENTS[event.index].tag);if(event.type==='precision')audio.sfx('medal');if(event.type==='flow')banner('FLOW STATE / '+event.count+' CLEAN CLEARS','+15 XP',1.8);if(event.type==='death'){resultTimer=.16;bank();}if(event.type==='complete')finish();}if(!bestCrossed&&game.targetBest>0&&game.distance>game.targetBest){bestCrossed=true;banner('PERSONAL BEST','Every meter from here is a new record.',2);audio.sfx('promotion');}coach();saveClock+=dt;if(saveClock>=1){bank();saveClock=0;showPromotion();}if(game.dead){resultTimer-=dt;if(resultTimer<=0)finish();}}hudClock+=dt;if(hudClock>=.08){updateHUD();hudClock=0;}}renderer.draw(game,save,dt,{menu:mode==='home'});audio.update(dt,mode==='run'&&!paused&&!game?.dead&&promotionTime<=0);requestAnimationFrame(frame);}
// Page-scoped helpers for agents; gameplay and UI use the same actions.
if(document.modelContext?.registerTool){const controller=new AbortController();const tools=[{name:'get_game_status',description:'Read Medal Run state, saved rank, and current run.',annotations:{readOnlyHint:true},execute:()=>({mode,paused,rank:rank(save.xp).name,stripes:rank(save.xp).stripes,xp:save.xp,coins:save.coins,distance:Math.floor(game?.distance||0)})},{name:'start_endless_run',description:'Start a new endless run from the menu or results screen.',annotations:{readOnlyHint:false},execute:()=>{if(mode==='run')throw Error('A run is already active.');start();return{started:true};}}];for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool({...tool,inputSchema:{type:'object',properties:{},additionalProperties:false},execute:input=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Expected an empty object');return tool.execute();}},{signal:controller.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>controller.abort(),{once:true});}
syncUnlocks();updateHome();if(store.error)$('save-status').textContent='SAVE UNAVAILABLE — USE EXPORT IN SETTINGS';requestAnimationFrame(frame);
