import {VERSION,COSMETICS,rank} from './data.js';
export const SAVE_KEY='medal-run-save';
const number=(v,fallback=0,max=1e12)=>Number.isFinite(v)&&v>=0?Math.min(v,max):fallback;
export function fresh(){return {version:VERSION,xp:0,coins:0,upgrades:{jump:0,luck:0},unlocks:COSMETICS.filter(x=>x.cost===0).map(x=>x.id),equipped:{gi:'gi-white',hair:'hair-original',rash:'rash-dark',patch:'patch-red',wrist:'wrist-blue'},achievements:[],seenHints:[],story:{completed:[]},stats:{runs:0,attempts:0,deaths:0,totalDistance:0,bestDistance:0,bestTime:0,playtime:0,coins:0,medals:0,bestClean:0,rollClears:0,doubleJumps:0,precision:0,highestSpeed:0,environments:[],legacyBest:0},settings:{sound:true,music:false,volume:.5,reducedMotion:false,hints:true},active:null};}
export function normalize(raw){const d=fresh();if(!raw||typeof raw!=='object')return d;for(const k of ['xp','coins'])d[k]=Math.floor(number(raw[k]));for(const k of ['jump','luck'])d.upgrades[k]=Math.floor(number(raw.upgrades?.[k],0,4));for(const key of ['unlocks','achievements','seenHints'])if(Array.isArray(raw[key]))d[key]=[...new Set([...d[key],...raw[key].filter(x=>typeof x==='string')])];for(const k of Object.keys(d.equipped)){const id=raw.equipped?.[k];if(d.unlocks.includes(id)&&COSMETICS.some(x=>x.id===id&&x.category===k))d.equipped[k]=id;}if(Array.isArray(raw.story?.completed))d.story.completed=[...new Set(raw.story.completed.filter(x=>typeof x==='string'))];for(const k of Object.keys(d.stats))if(k!=='environments')d.stats[k]=number(raw.stats?.[k]);d.stats.environments=Array.isArray(raw.stats?.environments)?[...new Set(raw.stats.environments.filter(v=>Number.isInteger(v)&&v>=0&&v<6))]:[];for(const k of ['sound','music','reducedMotion','hints'])if(typeof raw.settings?.[k]==='boolean')d.settings[k]=raw.settings[k];d.settings.volume=number(raw.settings?.volume,.5,1);if(raw.active&&typeof raw.active==='object')d.active={id:String(raw.active.id||''),time:number(raw.active.time),distance:number(raw.active.distance)};d.belt=rank(d.xp).name;d.stripes=rank(d.xp).stripes;return d;}
function checksum(s){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return(h>>>0).toString(16);}
function decode(text){try{const e=JSON.parse(text);if(!e||typeof e.payload!=='string'||e.check!==checksum(e.payload)||!Number.isFinite(e.seq))return null;return{seq:e.seq,data:normalize(JSON.parse(e.payload))};}catch{return null}}
export class SaveStore{constructor(storage){this.storage=storage;this.error=false;this.seq=0;this.data=this.load();}
load(){let a,b;try{a=decode(this.storage.getItem(SAVE_KEY));b=decode(this.storage.getItem(SAVE_KEY+'-backup'));}catch{this.error=true;}const good=[a,b].filter(Boolean).sort((x,y)=>y.seq-x.seq)[0];if(good){this.seq=good.seq;return good.data;}const d=fresh();try{d.stats.legacyBest=number(Number(this.storage.getItem('gabe-medal-best')));}catch{}return d;}
save(){try{this.data=normalize(this.data);const payload=JSON.stringify(this.data),envelope=JSON.stringify({seq:++this.seq,check:checksum(payload),payload});const prior=this.storage.getItem(SAVE_KEY);if(decode(prior))this.storage.setItem(SAVE_KEY+'-backup',prior);this.storage.setItem(SAVE_KEY,envelope);this.error=false;return true;}catch{this.error=true;return false;}}
export(){return JSON.stringify({game:'Gabe Medal Run',exportVersion:1,data:normalize(this.data)},null,2);}
import(text){let parsed;try{parsed=JSON.parse(text)}catch{throw new Error('This file is not a valid save.');}if(parsed?.game!=='Gabe Medal Run'||!parsed.data||!Number.isFinite(parsed.data.xp)||!Array.isArray(parsed.data.unlocks))throw new Error('Choose a Medal Run save file.');if(parsed.data.version>VERSION)throw new Error('This save needs a newer game version.');this.data=normalize(parsed.data);this.data.active=null;return this.save();}}
