// 100 stable daily IDs plus 12 curated Brown training puzzles.
// Repeated groups are capped at three appearances.
const ROUNDS = [

/* 1 */
[
["MARCELO GARCIA","ROGER GRACIE","BRUNO MALFACINE","RAFAEL MENDES","LEGENDS"],
["BUTTERFLY","X-GUARD","DE LA RIVA","SPIDER","GUARDS"],
["KIMURA","AMERICANA","ARMBAR","OMOPLATA","ARM ATTACKS"],
["TORIANDO","LEG DRAG","KNEE CUT","SMASH PASS","PASSES"]
],

/* 2 */
[
["GORDON RYAN","CRAIG JONES","NICK RODRIGUEZ","ANDREW WILTSE","NO-GI"],
["HEEL HOOK","KNEEBAR","STRAIGHT ANKLE","CALF SLICER","LEG ATTACKS"],
["ASHI GARAMI","SINGLE LEG X","INSIDE SANKAKU","OUTSIDE ASHI","LEG-LOCK POSITIONS"],
["SEATBELT","BODY TRIANGLE","HOOKS","BACK TAKE","BACK CONTROL"]
],

/* 3 */
[
["DEMIAN MAIA","ANDRE GALVAO","LEANDRO LO","MARCUS ALMEIDA","PRESSURE"],
["MOUNT","SIDE CONTROL","KESA","NORTH-SOUTH","TOP POSITIONS"],
["CROSS CHOKE","PAPER CUTTER","EZEKIEL","BOW-AND-ARROW","GI CHOKES"],
["SINGLE LEG","DOUBLE LEG","ANKLE PICK","UCHI MATA","TAKEDOWNS"]
],

/* 4 */
[
["DEAN LISTER","RUBENS CHARLES","GUI MENDES","RAFAEL MENDES","ALL-TIME GI STARS"],
["DE LA RIVA","BERIMBOLO","LASSO","COLLAR-SLEEVE","GI GUARDS"],
["GUILLOTINE","D'ARCE","ANACONDA","MARCELOTINE","HEAD-AND-NECK CHOKES"],
["ARMBAR","TRIANGLE","OMOPLATA","KIMURA","SUBMISSIONS"]
],

/* 5 */
[
["ROGER GRACIE","BUCHECHA","XANDE RIBEIRO","SAULO RIBEIRO","GRACIE-LINEAGE CHAMPIONS"],
["MOUNT","BACK","SIDE CONTROL","KNEE-ON-BELLY","POSITIONS"],
["STACK PASS","OVER-UNDER","DOUBLE UNDER","BODY LOCK","PRESSURE PASSES"],
["COLLAR CHOKE","CROSS CHOKE","CLOCK CHOKE","PAPER CUTTER","CHOKES"]
],

/* 6 */
[
["KAYNAN DUARTE","NICHOLAS MEREGALI","CRAIG JONES","JT TORRES","MODERN NO-GI"],
["HALF GUARD","DEEP HALF","KNEE SHIELD","Z-GUARD","HALF GUARDS"],
["HEEL HOOK","INSIDE SANKAKU","ASHI GARAMI","KNEEBAR","LEG LOCKS"],
["BODY LOCK","LEG DRAG","KNEE CUT","SMASH PASS","PASSES"]
],

/* 7 */
[
["MARCUS ALMEIDA","RODOLFO VIEIRA","ERBERTH SANTOS","LEANDRO LO","GI POWERHOUSES"],
["CLOSED GUARD","BUTTERFLY","SPIDER","DE LA RIVA","GUARDS"],
["MOUNT","BACK","SIDE CONTROL","NORTH-SOUTH","TOP CONTROL"],
["ARMBAR","TRIANGLE","KIMURA","AMERICANA","ARM SUBMISSIONS"]
],

/* 8 */
[
["MARCELO GARCIA","KRON GRACIE","DEMIAN MAIA","GORDON RYAN","SUBMISSION SPECIALISTS"],
["GUILLOTINE","ANACONDA","D'ARCE","PAPER CUTTER","CHOKES"],
["BERIMBOLO","BACK TAKE","ARM DRAG","TECHNICAL STAND-UP","BACK-TAKE TOOLS"],
["BUTTERFLY","X-GUARD","SINGLE LEG X","DEEP HALF","OPEN GUARDS"]
],

/* 9 */
[
["RAFAEL MENDES","GUI MENDES","MICA GALVAO","GABRIEL SOUSA","TECHNICAL GUARD PLAYERS"],
["DE LA RIVA","REVERSE DE LA RIVA","SPIDER","LASSO","OPEN GUARD"],
["BERIMBOLO","LEG DRAG","TORIANDO","KNEE CUT","GUARD-PASSING"],
["ARMBAR","OMOPLATA","TRIANGLE","KIMURA","ARM ATTACKS"]
],

/* 10 */
[
["JOHN DANAHER","KAYNAN DUARTE","GARRY TONON","CRAIG JONES","DANAHER-ASSOCIATED NO-GI"],
["HEEL HOOK","KNEEBAR","STRAIGHT ANKLE","CALF SLICER","LEG SUBMISSIONS"],
["ASHI GARAMI","SINGLE LEG X","INSIDE SANKAKU","OUTSIDE ASHI","LEG POSITIONS"],
["SEATBELT","BODY TRIANGLE","BACK TAKE","HOOKS","BACK CONTROL"]
],

/* 11 */
[
["ANDRE GALVAO","DEAN LISTER","SAULO RIBEIRO","ROMULO BARRAL","IBJJF LEGENDS"],
["CLOSED GUARD","BUTTERFLY","DEEP HALF","HALF GUARD","GUARDS"],
["MOUNT","SIDE CONTROL","KESA","NORTH-SOUTH","POSITIONS"],
["CROSS CHOKE","BOW-AND-ARROW","EZEKIEL","COLLAR CHOKE","GI CHOKES"]
],

/* 12 */
[
["BRUNO MALFACINE","CAIO TERRA","MIYAO BROTHERS","RAFAEL MENDES","LIGHTWEIGHT STARS"],
["SPIDER","DE LA RIVA","LASSO","COLLAR-SLEEVE","GI GUARDS"],
["POSTING HAND","POSTING FOOT","LIFTED HIPS","RETRACTING LEG","POSTS IN TECHNICAL STAND-UP","The posting hand and foot support lifted hips while the free leg retracts to stand."],
["TORIANDO","LEG DRAG","KNEE CUT","LONG STEP","PASSES"]
],

/* 13 */
[
["BUCHECHA","RODOLFO VIEIRA","GORDON RYAN","NICK RODRIGUEZ","HEAVYWEIGHT NO-GI NAMES"],
["MOUNT","SIDE CONTROL","NORTH-SOUTH","KESA","TOP POSITIONS"],
["BODY LOCK","SMASH PASS","STACK PASS","OVER-UNDER","PRESSURE PASSES"],
["GUILLOTINE","D'ARCE","ANACONDA","ARM TRIANGLE","CHOKES"]
],

/* 14 */
[
["MARCELO GARCIA","DEMIAN MAIA","ROGER GRACIE","KRON GRACIE","SUBMISSION-FOCUSED"],
["BUTTERFLY","CLOSED GUARD","HALF GUARD","DEEP HALF","GUARDS"],
["ARM DRAG","TECHNICAL STAND-UP","CHAIR SIT","BERIMBOLO","BACK TAKES"],
["REAR NAKED CHOKE","BOW-AND-ARROW","GUILLOTINE","D'ARCE","CHOKES"]
],

/* 15 */
[
["LEANDRO LO","MARCUS ALMEIDA","RUBENS CHARLES","RODOLFO VIEIRA","GI CHAMPIONS"],
["KIMURA","ARMBAR","AMERICANA","OMOPLATA","ARM ATTACKS"],
["MOUNT","BACK","SIDE CONTROL","KNEE-ON-BELLY","TOP POSITIONS"],
["SINGLE LEG","DOUBLE LEG","UCHI MATA","ANKLE PICK","TAKEDOWNS"]
],

/* 16 */
[
["KAYNAN DUARTE","CRAIG JONES","GARRY TONON","NICK RODRIGUEZ","NO-GI COMPETITORS"],
["HEEL HOOK","KNEEBAR","STRAIGHT ANKLE","CALF SLICER","LEG LOCKS"],
["ASHI GARAMI","SINGLE LEG X","INSIDE SANKAKU","OUTSIDE ASHI","LEG POSITIONS"],
["LEG DRAG","KNEE CUT","BODY LOCK","TORIANDO","PASSES"]
],

/* 17 */
[
["RAFAEL MENDES","GUI MENDES","MICA GALVAO","BRUNO MALFACINE","TECHNICAL LIGHTWEIGHTS"],
["DE LA RIVA","BERIMBOLO","SPIDER","LASSO","GI GUARDS"],
["LAPEL","COLLAR","SLEEVE","SKIRT","PARTS OF A GI JACKET","These are named parts of the gi jacket used for grips."],
["TORIANDO","LEG DRAG","LONG STEP","KNEE CUT","PASSES"]
],

/* 18 */
[
["ANDRE GALVAO","BUCHECHA","SAULO RIBEIRO","ROMULO BARRAL","GI LEGENDS"],
["CROSS CHOKE","COLLAR CHOKE","EZEKIEL","BOW-AND-ARROW","CHOKES"],
["MOUNT","SIDE CONTROL","BACK","NORTH-SOUTH","POSITIONS"],
["CLOSED GUARD","BUTTERFLY","HALF GUARD","DEEP HALF","GUARDS"]
],

/* 19 */
[
["DEAN LISTER","GORDON RYAN","DEMIAN MAIA","ROGER GRACIE","FAMOUS SUBMISSION STYLES"],
["GUILLOTINE","ANACONDA","D'ARCE","REAR NAKED CHOKE","CHOKES"],
["BUTTERFLY","X-GUARD","DE LA RIVA","SINGLE LEG X","GUARDS"],
["BACK TAKE","ARM DRAG","BERIMBOLO","CHAIR SIT","BACK ATTACKS"]
],

/* 20 */
[
["JOHN DANAHER","KAYNAN DUARTE","GARRY TONON","CRAIG JONES","DANAHER SYSTEM"],
["GABLE GRIP","S-GRIP","PALM-TO-PALM","WRIST-TO-WRIST","NO-GI HAND CONNECTIONS","These describe hand connections that do not rely on cloth."],
["FOREARM FRAME","SHIN FRAME","ELBOW FRAME","KNEE FRAME","FRAMES AGAINST TOP PRESSURE","These use limbs as structures to keep an opponent's weight away."],
["BODY LOCK","HALF GUARD","KNEE CUT","SMASH PASS","PASSING"]
],

/* 21 */
[
["RODOLFO VIEIRA","BUCHECHA","ERBERTH SANTOS","ROMULO BARRAL","POWERFUL GI"],
["SPRAWL","DOWN BLOCK","CROSSFACE","WHIZZER","WAYS TO STOP A SHOT","These are defensive tools against a leg attack, chosen according to position."],
["KIMURA","ARMBAR","AMERICANA","ARM TRIANGLE","ARM ATTACKS"],
["SINGLE LEG","DOUBLE LEG","ANKLE PICK","UCHI MATA","TAKEDOWNS"]
],

/* 22 */
[
["RAFAEL MENDES","GUI MENDES","BRUNO MALFACINE","CAIO TERRA","LIGHTWEIGHT TECHNIQUE"],
["SPIDER","LASSO","DE LA RIVA","COLLAR-SLEEVE","GUARDS"],
["BERIMBOLO","LEG DRAG","TORIANDO","KNEE CUT","PASSING"],
["RUN THE PIPE","SHELF THE LEG","LIFT AND RETURN","TRIP THE POST","SINGLE-LEG FINISHES","These describe ways of finishing a captured single leg."]
],

/* 23 */
[
["MARCELO GARCIA","KRON GRACIE","DEMIAN MAIA","ANDRE GALVAO","BACK-TAKE / SUBMISSION"],
["LEVEL CHANGE","PENETRATION STEP","TRAIL LEG","TURN THE CORNER","STEPS IN A DOUBLE-LEG SHOT","These are common components of a double-leg entry and finish."],
["ARM DRAG","BACK TAKE","BERIMBOLO","CHAIR SIT","BACK TAKES"],
["GUILLOTINE","ANACONDA","D'ARCE","REAR NAKED CHOKE","CHOKES"]
],

/* 24 */
[
["LACHLAN GILES","GARRY TONON","ETHAN CRELINSTEN","OLIVER TAZA","NO-GI COMPETITORS"],
["DOGFIGHT","KNEE TAP","ROLL UNDER","LIMP ARM","UNDERHOOK HALF-GUARD OPTIONS","These are positions or actions available in an underhook half-guard sequence."],
["OVER-SHOULDER ARM","UNDER-ARMPIT ARM","CONNECTED HANDS","CHEST-TO-BACK","CONTROLS IN A SEATBELT","These describe the structure of seatbelt back control."],
["SEATBELT","BODY TRIANGLE","HOOKS","BACK TAKE","BACK CONTROL"]
],

/* 25 */
[
["ROGER GRACIE","LEANDRO LO","MARCUS ALMEIDA","RUBENS CHARLES","GI"],
["MOUNT","BACK","SIDE CONTROL","KNEE-ON-BELLY","POSITIONS"],
["CROSS CHOKE","COLLAR CHOKE","EZEKIEL","BOW-AND-ARROW","GI CHOKES"],
["STACK PASS","OVER-UNDER","DOUBLE UNDER","BODY LOCK","PASSES"]
],

/* 26 */
[
["DEAN LISTER","RAFAEL MENDES","GUI MENDES","BRUNO MALFACINE","GI TECHNICIANS"],
["DE LA RIVA","SPIDER","LASSO","BUTTERFLY","GUARDS"],
["STANDING BREAK","KNEELING BREAK","SLEEVE CONTROL","HIP PIN","WAYS TO OPEN CLOSED GUARD","These are guard-opening actions or controls; the opening still needs a safe sequence."],
["TORIANDO","LEG DRAG","LONG STEP","KNEE CUT","PASSES"]
],

/* 27 */
[
["DEMIAN MAIA","ANDRE GALVAO","ROGER GRACIE","RUBENS CHARLES","SUBMISSION LEGENDS"],
["GUILLOTINE","D'ARCE","ANACONDA","REAR NAKED CHOKE","CHOKES"],
["FORWARD","BACKWARD","LEFT","RIGHT","DIRECTIONS FOR OFF-BALANCING","An opponent can be off-balanced along each of these directions."],
["BACK TAKE","ARM DRAG","BERIMBOLO","CHAIR SIT","BACK ATTACKS"]
],

/* 28 */
[
["KAYNAN DUARTE","CRAIG JONES","GARRY TONON","NICK RODRIGUEZ","NO-GI"],
["TURN TO THE SIDE","PLANT THE FOOT","MOVE THE HIPS","RECOVER SPACE","MOVEMENTS IN A SHRIMP","These describe the sequence of a basic hip escape."],
["CLOSED GUARD","BUTTERFLY","X-GUARD","K-GUARD","GUARDS"],
["BODY LOCK","SMASH PASS","LEG DRAG","KNEE CUT","PASSES"]
],

/* 29 */
[
["ROGER GRACIE","BUCHECHA","RODOLFO VIEIRA","XANDE RIBEIRO","GI HEAVYWEIGHTS"],
["TRAP THE ARM","TRAP THE FOOT","BRIDGE HIGH","ROLL DIAGONALLY","BRIDGE-AND-ROLL COMPONENTS","These are the core actions in a bridge-and-roll mount escape."],
["CROSS CHOKE","COLLAR CHOKE","EZEKIEL","PAPER CUTTER","CHOKES"],
["TOP SHIN","BOTTOM HOOK","FOREARM BARRIER","ELBOW-KNEE CONNECTION","STRUCTURES IN KNEE-SHIELD HALF","These help create distance and protect the inside space in knee-shield half guard."]
],

/* 30 */
[
["RAFAEL MENDES","GUI MENDES","MICA GALVAO","BRUNO MALFACINE","TECHNICAL GUARD PLAYERS"],
["DE LA RIVA","REVERSE DE LA RIVA","SPIDER","LASSO","OPEN GUARDS"],
["KNEE CUT","BODY LOCK","SMASH PASS","OVER-UNDER","PASSES"],
["TRIANGLE","ARMBAR","OMOPLATA","KIMURA","ARM ATTACKS"]
],

/* 31 */
[
["DEAN LISTER","DEMIAN MAIA","ANDRE GALVAO","GORDON RYAN","FAMOUS GRAPPLERS"],
["BUTTERFLY","X-GUARD","HALF GUARD","DEEP HALF","GUARDS"],
["REP DRILLING","FLOW DRILLING","POSITIONAL SPARRING","SITUATIONAL ROUNDS","PARTNER DRILL FORMATS","These are training formats that practice techniques with different constraints."],
["HIP ESCAPE","FORWARD ROLL","BACKWARD ROLL","SIT-THROUGH","SOLO MAT MOVEMENTS","These movements can be practiced without a partner."]
],

/* 32 */
[
["GORDON RYAN","NICKY RYAN","GARRY TONON","NICK RODRIGUEZ","DANAHER-ASSOCIATED NO-GI"],
["WORK INTERVAL","REST INTERVAL","ROUND COUNT","WARNING BELL","ROUND TIMER SETTINGS","These are settings commonly used to organize timed training rounds."],
["MOUTHGUARD","WATER BOTTLE","SPARE UNIFORM","PHOTO ID","COMPETITION BAG ESSENTIALS","These are useful items to pack; check the event's own requirements."],
["KNEE CUT","BODY LOCK","SMASH PASS","LEG DRAG","PASSES"]
],

/* 33 */
[
["LEANDRO LO","ROGER GRACIE","BUCHECHA","SAULO RIBEIRO","GI ICONS"],
["MOUNT","BACK","SIDE CONTROL","NORTH-SOUTH","POSITIONS"],
["WASH AFTER CLASS","COLD WASH","AIR DRY","CHECK CARE LABEL","GI LAUNDRY HABITS","These help keep training uniforms clean while following the garment's care instructions."],
["WHAT WORKED","WHAT FAILED","WHAT TO DRILL","WHAT TO ASK","BJJ JOURNAL PROMPTS","These questions turn a training session into a useful reflection."]
],

/* 34 */
[
["MICA GALVAO","TOMMY LANGAKER","ISAAC DOEDERLEIN","TOMOYUKI HASHIMOTO","LIGHTWEIGHTS"],
["SPIDER","LASSO","DE LA RIVA","COLLAR-SLEEVE","GUARDS"],
["BERIMBOLO","TORIANDO","LEG DRAG","KNEE CUT","PASSES"],
["TAP THE MAT","TAP THE BODY","VERBAL TAP","TAP WITH A FOOT","WAYS TO TAP","A clear tap communicates submission; a verbal tap is useful when the hands are trapped."]
],

/* 35 */
[
["LACHLAN GILES","GARRY TONON","CRAIG JONES","GORDON RYAN","SUBMISSION STYLE"],
["COLLAR GRIP","SLEEVE GRIP","PANT GRIP","BELT GRIP","GRIP CONTACT POINTS","These grips use different parts of the gi."],
["WRIST CONTROL","TRICEPS CONTROL","PULL ACROSS","ANGLE CHANGE","ARM-DRAG COMPONENTS","These controls and movements create an arm-drag opening."],
["HIP FRAMES","LEG PUMMELING","SHOULDER WALK","INVERSION","GUARD-RETENTION TOOLS","These create or recover space during guard retention."]
],

/* 36 */
[
["GORDON RYAN","CRAIG JONES","GARRY TONON","NICK RODRIGUEZ","MODERN NO-GI"],
["UNDERHOOK CONTROL","ELEVATING HOOK","SIDE FALL","BLOCKED POST","BUTTERFLY-SWEEP COMPONENTS","These components help lift and tip an opponent in a butterfly sweep."],
["CUT THE ANGLE","CONTROL THE HEAD","CLEAR THE SHOULDER","LOCK THE FIGURE FOUR","TRIANGLE ADJUSTMENTS","These are adjustments used to tighten a triangle after an entry."],
["BODY LOCK","SMASH PASS","KNEE CUT","OVER-UNDER","PASSES"]
],

/* 37 */
[
["RODOLFO VIEIRA","BUCHECHA","SAULO RIBEIRO","ERBERTH SANTOS","GI POWER"],
["WRIST CONTROL","PINCHED KNEES","THUMB ALIGNMENT","HIP EXTENSION","ARMBAR CONTROL POINTS","These controls and movements organize an armbar finish."],
["CROSS CHOKE","PAPER CUTTER","EZEKIEL","BOW-AND-ARROW","GI CHOKES"],
["WRIST HAND","THREADING ARM","OWN-WRIST GRIP","BENT ELBOW","KIMURA-GRIP COMPONENTS","These describe the figure-four grip and arm configuration used for a kimura."]
],

/* 38 */
[
["RAFAEL MENDES","GUI MENDES","MICA GALVAO","BRUNO MALFACINE","GUARD SPECIALISTS"],
["CLOSED GUARD","HALF GUARD","X-GUARD","KNEE SHIELD","GUARDS"],
["BERIMBOLO","LEG DRAG","TORIANDO","LONG STEP","PASSING"],
["PROTECT THE NECK","CONTROL CHOKING HAND","CLEAR A HOOK","SHOULDERS TO MAT","BACK-ESCAPE PRIORITIES","These are common goals in escaping back control, depending on the position."]
],

/* 39 */
[
["ROGER GRACIE","DEAN LISTER","DEMIAN MAIA","KRON GRACIE","LEGENDS"],
["CHIN STRAP","ELBOW CONTROL","HEAD PRESSURE","SPRAWLED HIPS","FRONT-HEADLOCK CONTROLS","These help control posture and movement from a front headlock."],
["WRIST PIN","ELBOW PIN","SHIN PIN","LEG TRAP","PINNING AN OPPONENT'S ARM","These describe ways to isolate an arm with a hand or limb."],
["ANKLE CONTROL","KNEE ACROSS","HIP BLOCK","CHEST CONNECTION","LEG-DRAG CONTROLS","These controls help move the legs aside and keep the hips turned in a leg drag."]
],

/* 40 */
[
["ADCC","IBJJF","EBI","POLARIS","GRAPPLING ORGANIZATIONS"],
["SCISSOR SWEEP","FLOWER SWEEP","HIP BUMP SWEEP","PENDULUM SWEEP","SWEEPS"],
["TOEHOLD","ESTIMA LOCK","ACHILLES LOCK","KNEEBAR","FOOT LOCKS"],
["UNDERHOOK","OVERHOOK","COLLAR TIE","PUMMELING","CLINCH POSITIONS"]
],

/* 41 */
[
["ANDRE GALVAO","BUCHECHA","LEANDRO LO","RODOLFO VIEIRA","GI CHAMPIONS"],
["MOUNT","BACK","SIDE CONTROL","KESA","POSITIONS"],
["LOCKED HANDS","HEAD POSITION","HIP PRESSURE","LEG CLEARANCE","BODY-LOCK PASS COMPONENTS","These components help connect to the hips and clear the opponent's legs."],
["STACK PASS","OVER-UNDER","DOUBLE UNDER","BODY LOCK","PASSES"]
],

/* 42 */
[
["MARCELO GARCIA","RAFAEL MENDES","GUI MENDES","BRUNO MALFACINE","GI TECHNICIANS"],
["UNDER-LEG ARM","OVER-LEG ARM","SHOULDER PRESSURE","HIP ANGLE","OVER-UNDER PASS COMPONENTS","These describe the asymmetric arm position and pressure of an over-under pass."],
["TWO UNDERHOOKS","STACKED HIPS","CONNECTED GRIP","CIRCLING FINISH","DOUBLE-UNDER PASS COMPONENTS","Both arms go under the legs before pressure and circling clear the guard."],
["SLICING KNEE","UNDERHOOK BATTLE","TRAILING FOOT","HIP CLEARANCE","KNEE-CUT PASS COMPONENTS","These are common control points in a knee-cut pass."]
],

/* 43 */
[
["DEMIAN MAIA","DEAN LISTER","ROGER GRACIE","KRON GRACIE","SUBMISSION ICONS"],
["POSTURE BREAK","OVERHOOK TRAP","ARM ACROSS","HIGH GUARD","CLOSED-GUARD ATTACK SETUPS","These create openings for attacks from closed guard."],
["WIDE KNEES","POSTED HAND","STAGGERED FEET","LOW HIPS","WAYS TO BUILD A BASE","These describe base adjustments used to resist being tipped over."],
["LIGHT","MODERATE","HARD","COMPETITION PACE","TRAINING INTENSITY WORDS","These describe intended training intensity; agree on pace with a partner."]
],

/* 44 */
[
["KAYNAN DUARTE","FELIPE PENA","VAGNER ROCHA","ETHAN CRELINSTEN","NO-GI STARS"],
["BOTTOM MOUNT","TOP HALF GUARD","BACK DEFENSE","TURTLE DEFENSE","POSITIONAL ROUND STARTS","These are specific starting situations for constrained sparring."],
["SPIDER GUARD","BUTTERFLY GUARD","OCTOPUS GUARD","WORM GUARD","GUARDS THAT NAME AN ANIMAL","Each of these guard names contains the name of an animal."],
["OVER-UNDER","DOUBLE UNDER","LEG OVER","STEP OVER","PASS NAMES WITH DIRECTIONS","These passing names describe going over or under a limb."]
],

/* 45 */
[
["LEANDRO LO","BUCHECHA","RODOLFO VIEIRA","ANDRE GALVAO","GI HEAVYWEIGHTS"],
["RETENTION","RECOVERY","PASSING","PULLING","WORDS AFTER 'GUARD'","Each word completes a common phrase beginning with guard."],
["KIMURA","AMERICANA","ARMBAR","ARM TRIANGLE","ARM ATTACKS"],
["TWO-ON-ONE","SINGLE LEG","DOUBLE LEG","50/50","TECHNIQUE NAMES WITH NUMBERS","These technique or position names contain a number or quantity."]
],

/* 46 */
[
["MARCELO GARCIA","CAIO TERRA","BRUNO MALFACINE","MIYAO BROTHERS","LIGHTWEIGHT STARS"],
["DE LA RIVA","SPIDER","LASSO","BUTTERFLY","GUARDS"],
["WRIST","HEAD","HIP","ELBOW","WORDS BEFORE 'CONTROL'","Each word can precede control to describe a grappling control point."],
["ARM","COLLAR","LEG","SLEEVE","WORDS BEFORE 'DRAG'","Each word completes a named grappling drag."]
],

/* 47 */
[
["ROGER GRACIE","MARCELO GARCIA","DEMIAN MAIA","GORDON RYAN","FAMOUS STYLISTS"],
["BUTTERFLY","X-GUARD","HALF GUARD","DEEP HALF","GUARDS"],
["POSTING HAND","POSTING FOOT","LIFTED HIPS","RETRACTING LEG","POSTS IN TECHNICAL STAND-UP","The posting hand and foot support lifted hips while the free leg retracts to stand."],
["LAPEL","COLLAR","SLEEVE","SKIRT","PARTS OF A GI JACKET","These are named parts of the gi jacket used for grips."]
],

/* 48 */
[
["KAYNAN DUARTE","CRAIG JONES","GARRY TONON","NICK RODRIGUEZ","NO-GI"],
["GABLE GRIP","S-GRIP","PALM-TO-PALM","WRIST-TO-WRIST","NO-GI HAND CONNECTIONS","These describe hand connections that do not rely on cloth."],
["FOREARM FRAME","SHIN FRAME","ELBOW FRAME","KNEE FRAME","FRAMES AGAINST TOP PRESSURE","These use limbs as structures to keep an opponent's weight away."],
["BODY LOCK","KNEE CUT","SMASH PASS","OVER-UNDER","PASSES"]
],

/* 49 */
[
["ANDRE GALVAO","LEANDRO LO","BUCHECHA","RODOLFO VIEIRA","GI LEGENDS"],
["SPRAWL","DOWN BLOCK","CROSSFACE","WHIZZER","WAYS TO STOP A SHOT","These are defensive tools against a leg attack, chosen according to position."],
["RUN THE PIPE","SHELF THE LEG","LIFT AND RETURN","TRIP THE POST","SINGLE-LEG FINISHES","These describe ways of finishing a captured single leg."],
["LEVEL CHANGE","PENETRATION STEP","TRAIL LEG","TURN THE CORNER","STEPS IN A DOUBLE-LEG SHOT","These are common components of a double-leg entry and finish."]
],

/* 50 */
[
["DEAN LISTER","RAFAEL MENDES","GORDON RYAN","ROGER GRACIE","ALL-TIME GREAT BJJ NAMES"],
["DE LA RIVA","BUTTERFLY","X-GUARD","SPIDER","GUARDS"],
["DOGFIGHT","KNEE TAP","ROLL UNDER","LIMP ARM","UNDERHOOK HALF-GUARD OPTIONS","These are positions or actions available in an underhook half-guard sequence."],
["LEG DRAG","TORIANDO","KNEE CUT","SMASH PASS","PASSES"]
],

/* 51 */
[
["OUTSIDE HEEL HOOK","TOEHOLD","ESTIMA LOCK","ACHILLES LOCK","LEG LOCK FINISHES"],
["BUGGY CHOKE","MONOPLATA","TWISTER","PERUVIAN NECKTIE","UNUSUAL SUBMISSIONS"],
["TRUCK","WEDGIE","MISSION CONTROL","BODY TRIANGLE","TRANSITIONAL POSITIONS"],
["TOMMY LANGAKER","VAGNER ROCHA","ETHAN CRELINSTEN","OLIVER TAZA","ACCOMPLISHED COMPETITORS"]
],

/* 52 */
[
["MISSION CONTROL","BODY TRIANGLE","SEATBELT","CRAB RIDE","TRANSITIONAL POSITIONS"],
["INSIDE SANKAKU","OUTSIDE ASHI","50/50","SADDLE","ADVANCED POSITIONS"],
["ESTIMA LOCK","ACHILLES LOCK","CALF SLICER","INSIDE HEEL HOOK","LEG LOCK FINISHES"],
["ETHAN CRELINSTEN","OLIVER TAZA","NICKY RYAN","KEENAN CORNELIUS","ACCOMPLISHED COMPETITORS"]
],

/* 53 */
[
["TRUCK","MISSION CONTROL","INSIDE SANKAKU","OUTSIDE ASHI","ADVANCED POSITIONS"],
["OUTSIDE HEEL HOOK","TOEHOLD","ESTIMA LOCK","ACHILLES LOCK","LEG LOCK FINISHES"],
["BUGGY CHOKE","MONOPLATA","TWISTER","PERUVIAN NECKTIE","UNUSUAL SUBMISSIONS"],
["OLIVER TAZA","NICKY RYAN","KEENAN CORNELIUS","MAHAMED ALY","ACCOMPLISHED COMPETITORS"]
],

/* 54 */
[
["CALF SLICER","INSIDE HEEL HOOK","OUTSIDE HEEL HOOK","TOEHOLD","LEG LOCK FINISHES"],
["VON FLUE CHOKE","GOGOPLATA","BUGGY CHOKE","MONOPLATA","UNUSUAL SUBMISSIONS"],
["SEATBELT","CRAB RIDE","TRUCK","WEDGIE","TRANSITIONAL POSITIONS"],
["NICKY RYAN","KEENAN CORNELIUS","MAHAMED ALY","ISAQUE BAHIENSE","ACCOMPLISHED COMPETITORS"]
],

/* 55 */
[
["TWISTER","PERUVIAN NECKTIE","VON FLUE CHOKE","GOGOPLATA","UNUSUAL SUBMISSIONS"],
["MISSION CONTROL","BODY TRIANGLE","SEATBELT","CRAB RIDE","TRANSITIONAL POSITIONS"],
["INSIDE SANKAKU","OUTSIDE ASHI","50/50","SADDLE","ADVANCED POSITIONS"],
["KEENAN CORNELIUS","MAHAMED ALY","ISAQUE BAHIENSE","TAINAN DALPRA","ACCOMPLISHED COMPETITORS"]
],

/* 56 */
[
["50/50","SADDLE","TRUCK","MISSION CONTROL","ADVANCED POSITIONS"],
["CALF SLICER","INSIDE HEEL HOOK","OUTSIDE HEEL HOOK","TOEHOLD","LEG LOCK FINISHES"],
["VON FLUE CHOKE","GOGOPLATA","BUGGY CHOKE","MONOPLATA","UNUSUAL SUBMISSIONS"],
["ISAQUE BAHIENSE","TAINAN DALPRA","ROBERTO JIMENEZ","LACHLAN GILES","ACCOMPLISHED COMPETITORS"]
],

/* 57 */
[
["ESTIMA LOCK","ACHILLES LOCK","CALF SLICER","INSIDE HEEL HOOK","LEG LOCK FINISHES"],
["TWISTER","PERUVIAN NECKTIE","VON FLUE CHOKE","GOGOPLATA","UNUSUAL SUBMISSIONS"],
["MISSION CONTROL","BODY TRIANGLE","SEATBELT","CRAB RIDE","TRANSITIONAL POSITIONS"],
["TAINAN DALPRA","ROBERTO JIMENEZ","LACHLAN GILES","TOMMY LANGAKER","ACCOMPLISHED COMPETITORS"]
],

/* 58 */
[
["INSIDE SANKAKU","OUTSIDE ASHI","50/50","SADDLE","ADVANCED POSITIONS"],
["ESTIMA LOCK","ACHILLES LOCK","CALF SLICER","INSIDE HEEL HOOK","LEG LOCK FINISHES"],
["TWISTER","PERUVIAN NECKTIE","VON FLUE CHOKE","GOGOPLATA","UNUSUAL SUBMISSIONS"],
["TOMMY LANGAKER","VAGNER ROCHA","ETHAN CRELINSTEN","OLIVER TAZA","ACCOMPLISHED COMPETITORS"]
],

/* 59 */
[
["CLOSED GUARD","HALF GUARD","BUTTERFLY","X-GUARD","GUARDS"],
["OVER-SHOULDER ARM","UNDER-ARMPIT ARM","CONNECTED HANDS","CHEST-TO-BACK","CONTROLS IN A SEATBELT","These describe the structure of seatbelt back control."],
["SCISSOR SWEEP","FLOWER SWEEP","HIP BUMP SWEEP","PENDULUM SWEEP","SWEEPS"],
["VAGNER ROCHA","ETHAN CRELINSTEN","OLIVER TAZA","NICKY RYAN","ACCOMPLISHED COMPETITORS"]
],

/* 60 */
[
["MOUNT","SIDE CONTROL","NORTH-SOUTH","KNEE-ON-BELLY","TOP POSITIONS"],
["KIMURA","AMERICANA","ARMBAR","OMOPLATA","ARM ATTACKS"],
["STANDING BREAK","KNEELING BREAK","SLEEVE CONTROL","HIP PIN","WAYS TO OPEN CLOSED GUARD","These are guard-opening actions or controls; the opening still needs a safe sequence."],
["OLIVER TAZA","NICKY RYAN","KEENAN CORNELIUS","MAHAMED ALY","ACCOMPLISHED COMPETITORS"]
],

/* 61 */
[
["FORWARD","BACKWARD","LEFT","RIGHT","DIRECTIONS FOR OFF-BALANCING","An opponent can be off-balanced along each of these directions."],
["CROSS CHOKE","PAPER CUTTER","CLOCK CHOKE","BOW-AND-ARROW","GI CHOKES"],
["STACK PASS","OVER-UNDER","DOUBLE UNDER","SMASH PASS","PRESSURE PASSES"],
["NICKY RYAN","KEENAN CORNELIUS","MAHAMED ALY","ISAQUE BAHIENSE","ACCOMPLISHED COMPETITORS"]
],

/* 62 */
[
["TURN TO THE SIDE","PLANT THE FOOT","MOVE THE HIPS","RECOVER SPACE","MOVEMENTS IN A SHRIMP","These describe the sequence of a basic hip escape."],
["HEEL HOOK","KNEEBAR","STRAIGHT ANKLE","TOEHOLD","LEG LOCKS"],
["TRAP THE ARM","TRAP THE FOOT","BRIDGE HIGH","ROLL DIAGONALLY","BRIDGE-AND-ROLL COMPONENTS","These are the core actions in a bridge-and-roll mount escape."],
["KEENAN CORNELIUS","MAHAMED ALY","ISAQUE BAHIENSE","TAINAN DALPRA","ACCOMPLISHED COMPETITORS"]
],

/* 63 */
[
["BUTTERFLY","X-GUARD","DEEP HALF","K-GUARD","OPEN GUARDS"],
["ARM DRAG","CHAIR SIT","CRAB RIDE","BERIMBOLO","BACK TAKES"],
["TOP SHIN","BOTTOM HOOK","FOREARM BARRIER","ELBOW-KNEE CONNECTION","STRUCTURES IN KNEE-SHIELD HALF","These help create distance and protect the inside space in knee-shield half guard."],
["MAHAMED ALY","ISAQUE BAHIENSE","TAINAN DALPRA","ROBERTO JIMENEZ","ACCOMPLISHED COMPETITORS"]
],

/* 64 */
[
["CLOSED GUARD","KNEE SHIELD","Z-GUARD","LOCKDOWN","GUARDS"],
["FLOWER SWEEP","HIP BUMP SWEEP","OLD SCHOOL SWEEP","ELECTRIC CHAIR SWEEP","SWEEPS"],
["BODY LOCK","KNEE CUT","LEG DRAG","TORIANDO","PASSES"],
["TAINAN DALPRA","ROBERTO JIMENEZ","LACHLAN GILES","TOMMY LANGAKER","ACCOMPLISHED COMPETITORS"]
],

/* 65 */
[
["REP DRILLING","FLOW DRILLING","POSITIONAL SPARRING","SITUATIONAL ROUNDS","PARTNER DRILL FORMATS","These are training formats that practice techniques with different constraints."],
["HIP ESCAPE","FORWARD ROLL","BACKWARD ROLL","SIT-THROUGH","SOLO MAT MOVEMENTS","These movements can be practiced without a partner."],
["WORK INTERVAL","REST INTERVAL","ROUND COUNT","WARNING BELL","ROUND TIMER SETTINGS","These are settings commonly used to organize timed training rounds."],
["ROBERTO JIMENEZ","LACHLAN GILES","TOMMY LANGAKER","VAGNER ROCHA","ACCOMPLISHED COMPETITORS"]
],

/* 66 */
[
["MOUTHGUARD","WATER BOTTLE","SPARE UNIFORM","PHOTO ID","COMPETITION BAG ESSENTIALS","These are useful items to pack; check the event's own requirements."],
["CROSS CHOKE","EZEKIEL","PAPER CUTTER","COLLAR CHOKE","GI CHOKES"],
["SINGLE LEG","DOUBLE LEG","RUSSIAN TIE","ANKLE PICK","TAKEDOWNS"],
["VAGNER ROCHA","ETHAN CRELINSTEN","OLIVER TAZA","NICKY RYAN","ACCOMPLISHED COMPETITORS"]
],

/* 67 */
[
["SPIDER","LASSO","WORM GUARD","DE LA RIVA","GI GUARDS"],
["WASH AFTER CLASS","COLD WASH","AIR DRY","CHECK CARE LABEL","GI LAUNDRY HABITS","These help keep training uniforms clean while following the garment's care instructions."],
["WHAT WORKED","WHAT FAILED","WHAT TO DRILL","WHAT TO ASK","BJJ JOURNAL PROMPTS","These questions turn a training session into a useful reflection."],
["ETHAN CRELINSTEN","OLIVER TAZA","NICKY RYAN","KEENAN CORNELIUS","ACCOMPLISHED COMPETITORS"]
],

/* 68 */
[
["BUTTERFLY","HALF GUARD","DEEP HALF","KNEE SHIELD","GUARDS"],
["SCISSOR SWEEP","FLOWER SWEEP","PENDULUM SWEEP","OLD SCHOOL SWEEP","SWEEPS"],
["TAP THE MAT","TAP THE BODY","VERBAL TAP","TAP WITH A FOOT","WAYS TO TAP","A clear tap communicates submission; a verbal tap is useful when the hands are trapped."],
["NICKY RYAN","KEENAN CORNELIUS","MAHAMED ALY","ISAQUE BAHIENSE","ACCOMPLISHED COMPETITORS"]
],

/* 69 */
[
["ASHI GARAMI","50/50","SADDLE","SINGLE LEG X","LEG POSITIONS"],
["TOEHOLD","KNEEBAR","STRAIGHT ANKLE","HEEL HOOK","LEG LOCKS"],
["COLLAR GRIP","SLEEVE GRIP","PANT GRIP","BELT GRIP","GRIP CONTACT POINTS","These grips use different parts of the gi."],
["KEENAN CORNELIUS","MAHAMED ALY","ISAQUE BAHIENSE","TAINAN DALPRA","ACCOMPLISHED COMPETITORS"]
],

/* 70 */
[
["CLOSED GUARD","X-GUARD","REVERSE DE LA RIVA","K-GUARD","OPEN GUARDS"],
["WRIST CONTROL","TRICEPS CONTROL","PULL ACROSS","ANGLE CHANGE","ARM-DRAG COMPONENTS","These controls and movements create an arm-drag opening."],
["HIP FRAMES","LEG PUMMELING","SHOULDER WALK","INVERSION","GUARD-RETENTION TOOLS","These create or recover space during guard retention."],
["MAHAMED ALY","ISAQUE BAHIENSE","TAINAN DALPRA","ROBERTO JIMENEZ","ACCOMPLISHED COMPETITORS"]
],

/* 71 */
[
["UNDERHOOK CONTROL","ELEVATING HOOK","SIDE FALL","BLOCKED POST","BUTTERFLY-SWEEP COMPONENTS","These components help lift and tip an opponent in a butterfly sweep."],
["LOCKDOWN","Z-GUARD","KNEE SHIELD","DEEP HALF","MODERN GUARDS"],
["GUILLOTINE","REAR NAKED CHOKE","LOOP CHOKE","BASEBALL CHOKE","CHOKES"],
["BRUNO MALFACINE","LEANDRO LO","RODOLFO VIEIRA","DEMIAN MAIA","ACCOMPLISHED COMPETITORS"]
],

/* 72 */
[
["TRUCK","WEDGIE","MISSION CONTROL","BODY TRIANGLE","TRANSITIONAL POSITIONS"],
["PUMMELING","RUSSIAN TIE","BODY LOCK","UNDERHOOK","CLINCH POSITIONS"],
["CUT THE ANGLE","CONTROL THE HEAD","CLEAR THE SHOULDER","LOCK THE FIGURE FOUR","TRIANGLE ADJUSTMENTS","These are adjustments used to tighten a triangle after an entry."],
["LEANDRO LO","RODOLFO VIEIRA","DEMIAN MAIA","KRON GRACIE","ACCOMPLISHED COMPETITORS"]
],

/* 73 */
[
["50/50","SADDLE","TRUCK","MISSION CONTROL","ADVANCED POSITIONS"],
["UAEJJF","WNO","ADCC","IBJJF","GRAPPLING ORGANIZATIONS"],
["SIDE CONTROL","NORTH-SOUTH","KESA","KNEE-ON-BELLY","TOP POSITIONS"],
["RODOLFO VIEIRA","DEMIAN MAIA","KRON GRACIE","SAULO RIBEIRO","ACCOMPLISHED COMPETITORS"]
],

/* 74 */
[
["WRIST CONTROL","PINCHED KNEES","THUMB ALIGNMENT","HIP EXTENSION","ARMBAR CONTROL POINTS","These controls and movements organize an armbar finish."],
["X-GUARD","CLOSED GUARD","BUTTERFLY","DE LA RIVA","GUARDS"],
["ANKLE PICK","UCHI MATA","ARM DRAG","RUSSIAN TIE","TAKEDOWNS"],
["DEMIAN MAIA","KRON GRACIE","SAULO RIBEIRO","XANDE RIBEIRO","ACCOMPLISHED COMPETITORS"]
],

/* 75 */
[
["BUGGY CHOKE","MONOPLATA","TWISTER","PERUVIAN NECKTIE","UNUSUAL SUBMISSIONS"],
["REAR NAKED CHOKE","LOOP CHOKE","BASEBALL CHOKE","NORTH-SOUTH CHOKE","CHOKES"],
["PENDULUM SWEEP","OLD SCHOOL SWEEP","ELECTRIC CHAIR SWEEP","SCISSOR SWEEP","SWEEPS"],
["KRON GRACIE","SAULO RIBEIRO","XANDE RIBEIRO","MICA GALVAO","ACCOMPLISHED COMPETITORS"]
],

/* 76 */
[
["SEATBELT","CRAB RIDE","TRUCK","WEDGIE","TRANSITIONAL POSITIONS"],
["KIMURA","AMERICANA","OMOPLATA","WRISTLOCK","ARM ATTACKS"],
["LONG STEP","STACK PASS","KNEE CUT","LEG DRAG","PASSES"],
["SAULO RIBEIRO","XANDE RIBEIRO","MICA GALVAO","RUBENS CHARLES","ACCOMPLISHED COMPETITORS"]
],

/* 77 */
[
["WRIST HAND","THREADING ARM","OWN-WRIST GRIP","BENT ELBOW","KIMURA-GRIP COMPONENTS","These describe the figure-four grip and arm configuration used for a kimura."],
["NORTH-SOUTH","KESA","KNEE-ON-BELLY","CRUCIFIX","TOP POSITIONS"],
["REVERSE DE LA RIVA","SPIDER","LASSO","COLLAR-SLEEVE","GI GUARDS"],
["XANDE RIBEIRO","MICA GALVAO","RUBENS CHARLES","ANDRE GALVAO","ACCOMPLISHED COMPETITORS"]
],

/* 78 */
[
["OUTSIDE HEEL HOOK","TOEHOLD","ESTIMA LOCK","ACHILLES LOCK","LEG LOCK FINISHES"],
["UCHI MATA","ARM DRAG","RUSSIAN TIE","SINGLE LEG","TAKEDOWNS"],
["K-GUARD","WORM GUARD","LOCKDOWN","Z-GUARD","MODERN GUARDS"],
["MICA GALVAO","RUBENS CHARLES","ANDRE GALVAO","BERNARDO FARIA","ACCOMPLISHED COMPETITORS"]
],

/* 79 */
[
["VON FLUE CHOKE","GOGOPLATA","BUGGY CHOKE","MONOPLATA","UNUSUAL SUBMISSIONS"],
["OLD SCHOOL SWEEP","ELECTRIC CHAIR SWEEP","SCISSOR SWEEP","FLOWER SWEEP","SWEEPS"],
["OVERHOOK","COLLAR TIE","PUMMELING","RUSSIAN TIE","CLINCH POSITIONS"],
["RUBENS CHARLES","ANDRE GALVAO","BERNARDO FARIA","CLAUDIO CALASANS","ACCOMPLISHED COMPETITORS"]
],

/* 80 */
[
["PROTECT THE NECK","CONTROL CHOKING HAND","CLEAR A HOOK","SHOULDERS TO MAT","BACK-ESCAPE PRIORITIES","These are common goals in escaping back control, depending on the position."],
["STACK PASS","KNEE CUT","LEG DRAG","SMASH PASS","PASSES"],
["EBI","POLARIS","UAEJJF","WNO","GRAPPLING ORGANIZATIONS"],
["ANDRE GALVAO","BERNARDO FARIA","CLAUDIO CALASANS","LUCAS LEPRI","ACCOMPLISHED COMPETITORS"]
],

/* 81 */
[
["CALF SLICER","INSIDE HEEL HOOK","OUTSIDE HEEL HOOK","TOEHOLD","LEG LOCK FINISHES"],
["WORM GUARD","LOCKDOWN","Z-GUARD","KNEE SHIELD","MODERN GUARDS"],
["BASEBALL CHOKE","NORTH-SOUTH CHOKE","CROSS CHOKE","EZEKIEL","CHOKES"],
["CLAUDIO CALASANS","LUCAS LEPRI","KAYNAN DUARTE","NICHOLAS MEREGALI","ACCOMPLISHED COMPETITORS"]
],

/* 82 */
[
["CHIN STRAP","ELBOW CONTROL","HEAD PRESSURE","SPRAWLED HIPS","FRONT-HEADLOCK CONTROLS","These help control posture and movement from a front headlock."],
["COLLAR TIE","PUMMELING","RUSSIAN TIE","BODY LOCK","CLINCH POSITIONS"],
["BICEP SLICER","ARMBAR","KIMURA","AMERICANA","ARM ATTACKS"],
["LUCAS LEPRI","KAYNAN DUARTE","NICHOLAS MEREGALI","YURI SIMOES","ACCOMPLISHED COMPETITORS"]
],

/* 83 */
[
["TRUCK","WEDGIE","MISSION CONTROL","BODY TRIANGLE","TRANSITIONAL POSITIONS"],
["POLARIS","UAEJJF","WNO","ADCC","GRAPPLING ORGANIZATIONS"],
["WRIST PIN","ELBOW PIN","SHIN PIN","LEG TRAP","PINNING AN OPPONENT'S ARM","These describe ways to isolate an arm with a hand or limb."],
["KAYNAN DUARTE","NICHOLAS MEREGALI","YURI SIMOES","DEAN LISTER","ACCOMPLISHED COMPETITORS"]
],

/* 84 */
[
["50/50","SADDLE","TRUCK","MISSION CONTROL","ADVANCED POSITIONS"],
["HALF GUARD","X-GUARD","CLOSED GUARD","BUTTERFLY","GUARDS"],
["DOUBLE LEG","ANKLE PICK","UCHI MATA","ARM DRAG","TAKEDOWNS"],
["NICHOLAS MEREGALI","YURI SIMOES","DEAN LISTER","RENZO GRACIE","ACCOMPLISHED COMPETITORS"]
],

/* 85 */
[
["ANKLE CONTROL","KNEE ACROSS","HIP BLOCK","CHEST CONNECTION","LEG-DRAG CONTROLS","These controls help move the legs aside and keep the hips turned in a leg drag."],
["NORTH-SOUTH CHOKE","CROSS CHOKE","EZEKIEL","BOW-AND-ARROW","CHOKES"],
["HIP BUMP SWEEP","PENDULUM SWEEP","OLD SCHOOL SWEEP","ELECTRIC CHAIR SWEEP","SWEEPS"],
["YURI SIMOES","DEAN LISTER","RENZO GRACIE","FELIPE PENA","ACCOMPLISHED COMPETITORS"]
],

/* 86 */
[
["WRISTLOCK","BICEP SLICER","ARMBAR","KIMURA","ARM ATTACKS"],
["DOUBLE LEG","ANKLE PICK","UCHI MATA","ARM DRAG","TAKEDOWNS"],
["DE LA RIVA","REVERSE DE LA RIVA","SPIDER","LASSO","GI GUARDS"],
["DEAN LISTER","RENZO GRACIE","FELIPE PENA","CRAIG JONES","WELL-KNOWN COMPETITORS"]
],

/* 87 */
[
["CRUCIFIX","MOUNT","SIDE CONTROL","NORTH-SOUTH","TOP POSITIONS"],
["HIP BUMP SWEEP","PENDULUM SWEEP","OLD SCHOOL SWEEP","ELECTRIC CHAIR SWEEP","SWEEPS"],
["DEEP HALF","K-GUARD","WORM GUARD","LOCKDOWN","MODERN GUARDS"],
["RENZO GRACIE","FELIPE PENA","CRAIG JONES","GARRY TONON","WELL-KNOWN COMPETITORS"]
],

/* 88 */
[
["LOCKED HANDS","HEAD POSITION","HIP PRESSURE","LEG CLEARANCE","BODY-LOCK PASS COMPONENTS","These components help connect to the hips and clear the opponent's legs."],
["TORIANDO","LONG STEP","STACK PASS","KNEE CUT","PASSES"],
["UNDERHOOK","OVERHOOK","COLLAR TIE","PUMMELING","CLINCH POSITIONS"],
["FELIPE PENA","CRAIG JONES","GARRY TONON","NICK RODRIGUEZ","WELL-KNOWN COMPETITORS"]
],

/* 89 */
[
["FLOWER SWEEP","HIP BUMP SWEEP","PENDULUM SWEEP","OLD SCHOOL SWEEP","SWEEPS"],
["UNDER-LEG ARM","OVER-LEG ARM","SHOULDER PRESSURE","HIP ANGLE","OVER-UNDER PASS COMPONENTS","These describe the asymmetric arm position and pressure of an over-under pass."],
["IBJJF","EBI","POLARIS","UAEJJF","GRAPPLING ORGANIZATIONS"],
["CRAIG JONES","GARRY TONON","NICK RODRIGUEZ","JOHN DANAHER","WELL-KNOWN COMPETITORS"]
],

/* 90 */
[
["SMASH PASS","TORIANDO","LONG STEP","STACK PASS","PASSES"],
["DEEP HALF","K-GUARD","WORM GUARD","LOCKDOWN","MODERN GUARDS"],
["DE LA RIVA","SPIDER","HALF GUARD","X-GUARD","GUARDS"],
["GARRY TONON","NICK RODRIGUEZ","JOHN DANAHER","GORDON RYAN","WELL-KNOWN COMPETITORS"]
],

/* 91 */
[
["WORM GUARD","DE LA RIVA","REVERSE DE LA RIVA","SPIDER","GI GUARDS"],
["UNDERHOOK","OVERHOOK","COLLAR TIE","PUMMELING","CLINCH POSITIONS"],
["EZEKIEL","BOW-AND-ARROW","GUILLOTINE","REAR NAKED CHOKE","CHOKES"],
["NICK RODRIGUEZ","JOHN DANAHER","GORDON RYAN","MARCELO GARCIA","WELL-KNOWN COMPETITORS"]
],

/* 92 */
[
["KNEE SHIELD","DEEP HALF","K-GUARD","WORM GUARD","MODERN GUARDS"],
["IBJJF","EBI","POLARIS","UAEJJF","GRAPPLING ORGANIZATIONS"],
["WRISTLOCK","BICEP SLICER","ARMBAR","KIMURA","ARM ATTACKS"],
["JOHN DANAHER","GORDON RYAN","MARCELO GARCIA","RAFAEL MENDES","WELL-KNOWN COMPETITORS"]
],

/* 93 */
[
["BODY LOCK","UNDERHOOK","OVERHOOK","COLLAR TIE","CLINCH POSITIONS"],
["DE LA RIVA","SPIDER","HALF GUARD","X-GUARD","GUARDS"],
["CRUCIFIX","MOUNT","SIDE CONTROL","NORTH-SOUTH","TOP POSITIONS"],
["GORDON RYAN","MARCELO GARCIA","RAFAEL MENDES","GUI MENDES","WELL-KNOWN COMPETITORS"]
],

/* 94 */
[
["ADCC","IBJJF","EBI","POLARIS","GRAPPLING ORGANIZATIONS"],
["EZEKIEL","BOW-AND-ARROW","GUILLOTINE","REAR NAKED CHOKE","CHOKES"],
["TWO UNDERHOOKS","STACKED HIPS","CONNECTED GRIP","CIRCLING FINISH","DOUBLE-UNDER PASS COMPONENTS","Both arms go under the legs before pressure and circling clear the guard."],
["MARCELO GARCIA","RAFAEL MENDES","GUI MENDES","BRUNO MALFACINE","WELL-KNOWN COMPETITORS"]
],

/* 95 */
[
["BUTTERFLY","DE LA RIVA","SPIDER","HALF GUARD","GUARDS"],
["WRISTLOCK","BICEP SLICER","ARMBAR","KIMURA","ARM ATTACKS"],
["FLOWER SWEEP","HIP BUMP SWEEP","PENDULUM SWEEP","OLD SCHOOL SWEEP","SWEEPS"],
["RAFAEL MENDES","GUI MENDES","BRUNO MALFACINE","LEANDRO LO","WELL-KNOWN COMPETITORS"]
],

/* 96 */
[
["CROSS CHOKE","EZEKIEL","BOW-AND-ARROW","GUILLOTINE","CHOKES"],
["CRUCIFIX","MOUNT","SIDE CONTROL","NORTH-SOUTH","TOP POSITIONS"],
["SMASH PASS","TORIANDO","LONG STEP","STACK PASS","PASSES"],
["GUI MENDES","BRUNO MALFACINE","LEANDRO LO","RODOLFO VIEIRA","WELL-KNOWN COMPETITORS"]
],

/* 97 */
[
["OMOPLATA","WRISTLOCK","BICEP SLICER","ARMBAR","ARM ATTACKS"],
["SLICING KNEE","UNDERHOOK BATTLE","TRAILING FOOT","HIP CLEARANCE","KNEE-CUT PASS COMPONENTS","These are common control points in a knee-cut pass."],
["WORM GUARD","DE LA RIVA","REVERSE DE LA RIVA","SPIDER","GI GUARDS"],
["BRUNO MALFACINE","LEANDRO LO","RODOLFO VIEIRA","DEMIAN MAIA","WELL-KNOWN COMPETITORS"]
],

/* 98 */
[
["KNEE-ON-BELLY","CRUCIFIX","MOUNT","SIDE CONTROL","TOP POSITIONS"],
["FLOWER SWEEP","HIP BUMP SWEEP","PENDULUM SWEEP","OLD SCHOOL SWEEP","SWEEPS"],
["KNEE SHIELD","DEEP HALF","K-GUARD","WORM GUARD","MODERN GUARDS"],
["LEANDRO LO","RODOLFO VIEIRA","DEMIAN MAIA","KRON GRACIE","WELL-KNOWN COMPETITORS"]
],

/* 99 */
[
["RUSSIAN TIE","SINGLE LEG","DOUBLE LEG","ANKLE PICK","TAKEDOWNS"],
["SMASH PASS","TORIANDO","LONG STEP","STACK PASS","PASSES"],
["BODY LOCK","UNDERHOOK","OVERHOOK","COLLAR TIE","CLINCH POSITIONS"],
["RODOLFO VIEIRA","DEMIAN MAIA","KRON GRACIE","SAULO RIBEIRO","WELL-KNOWN COMPETITORS"]
],

/* 100 */
[
["SCISSOR SWEEP","FLOWER SWEEP","HIP BUMP SWEEP","PENDULUM SWEEP","SWEEPS"],
["WORM GUARD","DE LA RIVA","REVERSE DE LA RIVA","SPIDER","GI GUARDS"],
["ADCC","IBJJF","EBI","POLARIS","GRAPPLING ORGANIZATIONS"],
["DEMIAN MAIA","KRON GRACIE","SAULO RIBEIRO","XANDE RIBEIRO","WELL-KNOWN COMPETITORS"]
]
];

// ---------------------------------------------------------------------
// Real "Learn why" explanations, keyed by exact category string.
// One or two honest sentences about what the category actually is —
// not just the category name repeated back. Kept general/descriptive
// rather than making specific superlative claims about any one person.
// A category not found here falls back to a generic sentence so a
// future puzzle with a new category name never breaks the UI.
// ---------------------------------------------------------------------
const EXPLANATIONS = {
  "GUARDS": "General term for defensive positions played from the bottom, using the legs to control distance, off-balance an opponent, and set up attacks from underneath.",
  "PASSES": "Guard passes are techniques a top player uses to get around an opponent's legs and into a dominant position.",
  "CHOKES": "Chokes cut off blood flow or air through the neck to force a tap — among the most common finishes in both gi and no-gi.",
  "SUBMISSIONS": "General term for any technique — a choke, joint lock, or compression — used to force an opponent to submit.",
  "POSITIONS": "Core control positions in jiu-jitsu, each with its own hierarchy of dominance and typical attacking options.",
  "LEG POSITIONS": "Control positions used to enter and finish leg locks, developed and popularized in the modern no-gi leg-lock era.",
  "ARM ATTACKS": "Joint locks that target the elbow or shoulder to force a submission.",
  "LEG LOCKS": "Submissions that attack the knee, ankle, or hip through the leg — a major focus of modern no-gi grappling.",
  "TAKEDOWNS": "Techniques used to bring a standing opponent to the mat, many borrowed from wrestling and judo.",
  "NO-GI": "A ruleset and style of grappling practiced without a gi, which changes grips and often opens up leg-lock-heavy game plans.",
  "BACK CONTROL": "The dominant back position, usually combined with hooks or a body triangle, from which many chokes are finished.",
  "TOP POSITIONS": "Dominant positions controlled from on top of the opponent, offering strong attacking angles with lower risk.",
  "BACK ATTACKS": "Techniques and entries used to take or maintain an opponent's back, one of the most valuable positions in grappling.",
  "PASSING": "The family of techniques used to get past an opponent's legs into a dominant position.",
  "LEG ATTACKS": "Another term for leg locks — submissions that target the ankle, knee, or hip.",
  "GI CHOKES": "Chokes that use the collar or lapel of the gi for extra leverage, unavailable in no-gi grappling.",
  "GI GUARDS": "Guard variations that rely on gripping the opponent's gi — collar, sleeve, or pants — for control.",
  "BACK TAKES": "Techniques and entries used specifically to get to an opponent's back.",
  "LEGENDS": "Widely regarded as among the most influential competitors in jiu-jitsu history.",
  "PRESSURE PASSES": "Guard passes that rely on heavy top pressure and weight distribution rather than speed.",
  "MODERN NO-GI": "Competitors associated with the current generation of no-gi grappling and its leg-lock-heavy meta.",
  "TOP CONTROL": "Positions and techniques used to maintain dominant control from the top.",
  "OPEN GUARDS": "Guard variations played without the legs closed around the opponent's torso, usually more mobile than closed guard.",
  "TECHNICAL GUARD PLAYERS": "Known for a detailed, technique-heavy guard game rather than relying on athleticism alone.",
  "GI CHAMPIONS": "Competitors known for their success specifically in gi competition.",
  "GI LEGENDS": "Widely regarded among the most accomplished competitors in gi jiu-jitsu.",
  "GI TECHNICIANS": "Known for precise, detail-oriented technique within the gi ruleset.",
  "GI HEAVYWEIGHTS": "Accomplished competitors who competed primarily in the heavier gi weight classes.",
  "LEG-LOCK POSITIONS": "Control positions used to enter and finish leg-lock submissions.",
  "PRESSURE": "Known for a heavy, pressure-based style of top control.",
  "ALL-TIME GI STARS": "Among the most decorated and recognizable names in gi competition history.",
  "HEAD-AND-NECK CHOKES": "Submissions that finish by choking through the neck, using an arm, the collar, or a combination of both.",
  "GRACIE-LINEAGE CHAMPIONS": "Competitors from the Gracie family lineage who became major competition champions.",
  "HALF GUARDS": "Guard variations played with one leg trapped between the opponent's legs.",
  "GI POWERHOUSES": "Known for strong, physically dominant performances in gi competition.",
  "ARM SUBMISSIONS": "Submissions that finish by attacking the arm.",
  "SUBMISSION SPECIALISTS": "Known for finishing a high percentage of matches by submission rather than by points.",
  "BACK-TAKE TOOLS": "Techniques used specifically to get to and secure an opponent's back.",
  "OPEN GUARD": "A family of guards played without closing the legs around the opponent.",
  "GUARD-PASSING": "Techniques used to get around an opponent's guard and into a dominant position.",
  "DANAHER-ASSOCIATED NO-GI": "Competitors associated with coach John Danaher's leg-lock-focused no-gi system.",
  "LEG SUBMISSIONS": "Submissions that finish by attacking the leg.",
  "IBJJF LEGENDS": "Among the most decorated competitors in IBJJF (International Brazilian Jiu-Jitsu Federation) competition history.",
  "LIGHTWEIGHT STARS": "Accomplished competitors known for competing in the lighter weight classes.",
  "HEAVYWEIGHT NO-GI NAMES": "Accomplished competitors known for no-gi competition in the heavier weight classes.",
  "SUBMISSION-FOCUSED": "Known for an aggressive, finish-first competitive style.",
  "NO-GI COMPETITORS": "Competitors who built their reputation primarily in no-gi competition.",
  "TECHNICAL LIGHTWEIGHTS": "Lighter-weight competitors known for detailed, technique-driven grappling.",
  "FAMOUS SUBMISSION STYLES": "Known for a distinctive, submission-hunting competitive style.",
  "DANAHER SYSTEM": "Competitors associated with the systematic leg-lock and back-attack approach developed by coach John Danaher.",
  "POWERFUL GI": "Known for a strong, pressure-heavy game within the gi ruleset.",
  "LIGHTWEIGHT TECHNIQUE": "Lighter-weight competitors recognized for technical, detail-focused grappling.",
  "BACK-TAKE / SUBMISSION": "Known for combining back takes with high finishing rates.",
  "GI": "Accomplished competitors within the gi ruleset.",
  "SUBMISSION LEGENDS": "Among the most recognizable submission specialists in the sport's history.",
  "FAMOUS GRAPPLERS": "Widely recognized names across jiu-jitsu and grappling.",
  "LEG-LOCK ERA": "Competitors associated with the rise of leg locks as a mainstream competitive weapon.",
  "GI ICONS": "Widely recognized figures in gi competition history.",
  "LIGHTWEIGHTS": "Accomplished competitors in the lighter weight classes.",
  "SUBMISSION STYLE": "Known for a particular, recognizable approach to finishing fights.",
  "GI POWER": "Known for a strong, physically dominant style within the gi ruleset.",
  "GUARD SPECIALISTS": "Known for an especially technical or dangerous guard game.",
  "SUBMISSION ICONS": "Widely recognized for a submission-focused competitive style.",
  "NO-GI STARS": "Well-known competitors within the no-gi ruleset.",
  "TECHNICAL BJJ": "Known for detail-oriented, technique-driven grappling.",
  "FAMOUS STYLISTS": "Recognized for a signature style of grappling.",
  "ALL-TIME GREAT BJJ NAMES": "Among the most recognizable names across jiu-jitsu history.",
  "GRAPPLING ORGANIZATIONS": "Major organizations and events that host high-level grappling competition.",
  "SWEEPS": "Sweeps are guard techniques used to reverse position from the bottom, turning a bottom player into the top player.",
  "FOOT LOCKS": "Submissions that attack the foot or ankle — a specialized branch of leg locks.",
  "CLINCH POSITIONS": "Grip and control positions used in the stand-up clinch, often as entries into takedowns.",
  "ADVANCED POSITIONS": "Specialized controls used during guard, leg-lock and back-attack exchanges.",
  "LEG LOCK FINISHES": "Submissions that finish a leg entanglement, ranging from footlocks to the two variations of the heel hook.",
  "UNUSUAL SUBMISSIONS": "Less common finishes targeting different joints or the neck, including omoplata variations and spinal locks.",
  "TRANSITIONAL POSITIONS": "Control positions used mid-sequence — often on the way to the back or into a leg entanglement — rather than as an end position themselves.",
  "ACCOMPLISHED COMPETITORS": "Competitors with strong records at the top levels of gi and no-gi competition.",
  "WELL-KNOWN COMPETITORS": "Widely recognized names across professional jiu-jitsu competition.",
  "MODERN GUARDS": "Guard variations that rose to prominence more recently in high-level competition, several tied to a specific competitor who popularized them."
};
function explanationFor(category, items) {
  return EXPLANATIONS[category] || `A recognized grouping in jiu-jitsu: ${items.join(", ")}.`;
}

// ---------------------------------------------------------------------
// Difficulty is classified from the puzzle's actual content — and, since
// a puzzle is genuinely hard only when MOST of it is hard, this looks at
// how many of the 4 groups are advanced, not just whether any single
// group is. (Earlier versions of this file called a puzzle "black belt"
// if even one group was a leg-lock group, even when the other three were
// plain fundamentals — that made "black belt" mean almost nothing.)
//
// BLACK_BELT_TERMS: material a white or blue belt typically hasn't seen.
// PURPLE_BELT_TERMS: intermediate material — beyond fundamentals, short
//   of the deep leg-lock/back-attack system vocabulary.
// WHITE_BELT_TERMS: true fundamentals, taught in the first weeks/months.
// ADVANCED_NAME_POOL: real competitors known specifically within the
//   high-level no-gi/leg-lock scene rather than mainstream name-recognition
//   — correctly recognizing them is itself a sign of deeper knowledge.
// ---------------------------------------------------------------------
const BLACK_BELT_TERMS = new Set(["HEEL HOOK","KNEEBAR","CALF SLICER","STRAIGHT ANKLE","ASHI GARAMI",
  "INSIDE SANKAKU","OUTSIDE ASHI","SINGLE LEG X","ESTIMA LOCK","ACHILLES LOCK","TOEHOLD","MARCELOTINE",
  "INSIDE HEEL HOOK","OUTSIDE HEEL HOOK","50/50","SADDLE","TRUCK","MISSION CONTROL","TWISTER",
  "PERUVIAN NECKTIE","VON FLUE CHOKE","GOGOPLATA","BUGGY CHOKE","MONOPLATA","CRAB RIDE","WEDGIE",
  "CRUCIFIX","BICEP SLICER","WRISTLOCK","LOOP CHOKE","BASEBALL CHOKE","NORTH-SOUTH CHOKE"]);
const PURPLE_BELT_TERMS = new Set(["BERIMBOLO","LASSO","REVERSE DE LA RIVA","TORIANDO","LONG STEP",
  "CHAIR SIT","TECHNICAL STAND-UP","ARM DRAG","SEATBELT","BODY TRIANGLE","KNEE CUT","SMASH PASS",
  "STACK PASS","OVER-UNDER","DOUBLE UNDER","BODY LOCK","SPIDER","DE LA RIVA","COLLAR-SLEEVE","X-GUARD",
  "DEEP HALF","HALF GUARD","KNEE SHIELD","Z-GUARD","KNEE-ON-BELLY","NORTH-SOUTH","KESA","K-GUARD",
  "WORM GUARD","LOCKDOWN","OLD SCHOOL SWEEP","ELECTRIC CHAIR SWEEP","RUSSIAN TIE","UNDERHOOK",
  "OVERHOOK","COLLAR TIE","PUMMELING"]);
const WHITE_BELT_TERMS = new Set(["MOUNT","SIDE CONTROL","CLOSED GUARD","BUTTERFLY","CROSS CHOKE",
  "COLLAR CHOKE","ARMBAR","KIMURA","AMERICANA","TRIANGLE","SINGLE LEG","DOUBLE LEG","UCHI MATA",
  "ANKLE PICK","EZEKIEL","REAR NAKED CHOKE","GUILLOTINE","BACK TAKE","HOOKS"]);
const ADVANCED_NAME_POOL = new Set(["LACHLAN GILES","TOMMY LANGAKER","VAGNER ROCHA","ETHAN CRELINSTEN",
  "OLIVER TAZA","NICKY RYAN","KEENAN CORNELIUS","MAHAMED ALY","ISAQUE BAHIENSE","TAINAN DALPRA",
  "ROBERTO JIMENEZ"]);

function classifyDifficulty(groups) {
  // A group counts as "advanced" if at least 3 of its 4 items are
  // black-tier terms (or advanced-tier names) — i.e. the group as a
  // whole, not just a stray word, is genuinely deep material.
  const advancedGroupCount = groups.filter(items => {
    const hits = items.filter(w => BLACK_BELT_TERMS.has(w) || ADVANCED_NAME_POOL.has(w)).length;
    return hits >= 3;
  }).length;

  // Black belt requires real breadth: at least half the puzzle (2 of its
  // 4 groups) has to be advanced-tier, not just one isolated group.
  if (advancedGroupCount >= 2) return "black";
  // Exactly one deep group, or a lighter dusting of advanced material
  // spread thinner, reads as purple — real exposure, not a full system.
  if (advancedGroupCount === 1) return "purple";

  const items = groups.flat();
  let score = 0;
  items.forEach(w => {
    if (PURPLE_BELT_TERMS.has(w)) score += 1;
    else if (WHITE_BELT_TERMS.has(w)) score -= 1;
  });
  if (score <= -2) return "white";
  if (score <= 2) return "blue";
  return "purple";
}

const DAILY_PUZZLES = ROUNDS.map((groups, index) => {
  const builtGroups = groups.map(g => ({
    items: g.slice(0, 4),
    category: g[4],
    explanation: g[5] || explanationFor(g[4], g.slice(0, 4))
  }));
  return {
    id: index + 1,
    groups: builtGroups,
    difficulty: classifyDifficulty(builtGroups.map(g => g.items))
  };
});

// Brown emphasizes connected systems and positional detail. These curated
// rounds extend practice without changing historical daily/archive assignments.
const BROWN_ROUNDS = [
  [
    [
      "WORM GUARD",
      "SQUID GUARD",
      "LAPEL LASSO",
      "RINGWORM GUARD",
      "LAPEL GUARD SYSTEMS",
      "These gi guards use the lapel as an additional control around the legs or body."
    ],
    [
      "CRAB RIDE",
      "CHAIR SIT",
      "ROLLING BACK TAKE",
      "KISS OF THE DRAGON",
      "ROUTES TO THE BACK",
      "These entries connect a transitional control or rotation to back control."
    ],
    [
      "KNEE LINE",
      "HEEL EXPOSURE",
      "SECONDARY LEG",
      "HIP ALIGNMENT",
      "LEG ENTANGLEMENT CHECKPOINTS",
      "These details describe control and alignment during a leg-entanglement exchange."
    ],
    [
      "CROSSFACE",
      "HIP BLOCK",
      "UNDERHOOK",
      "SHOULDER PRESSURE",
      "UPPER-BODY PASSING CONTROLS",
      "These controls help a passer limit turning and movement before settling a pass."
    ]
  ],
  [
    [
      "LEG PUMMEL",
      "HIGH LEG",
      "HIP SCOOT",
      "SHOULDER ROLL",
      "GUARD RETENTION MOVEMENTS",
      "These movements help recover inside position or redirect the hips during a passing exchange."
    ],
    [
      "LONG STEP",
      "LEG DRAG",
      "TORIANDO",
      "X-PASS",
      "MOBILE PASSING OPTIONS",
      "These passes change the angle around the legs rather than staying in one straight path."
    ],
    [
      "LAPEL FEED",
      "CROSS-COLLAR GRIP",
      "SLEEVE CUFF",
      "PANTS GRIP",
      "GI GRIP CONNECTIONS",
      "Each is a way to establish or transfer control using the gi."
    ],
    [
      "ARM TRIANGLE",
      "D'ARCE",
      "ANACONDA",
      "NORTH-SOUTH CHOKE",
      "ARM-BASED CHOKES",
      "These chokes use upper-body positioning without requiring a collar grip."
    ]
  ],
  [
    [
      "REVERSE DE LA RIVA",
      "K-GUARD",
      "DEEP HALF",
      "BUTTERFLY HALF",
      "GUARDS WITH LOWER-BODY ENTRIES",
      "These guards can connect underneath the opponent to sweeps or lower-body control."
    ],
    [
      "DOUBLE UNDER",
      "OVER-UNDER",
      "STACK PASS",
      "BODY LOCK PASS",
      "CLOSE-DISTANCE PASSING",
      "These passes rely on closing distance and controlling the hips or legs."
    ],
    [
      "WRIST RIDE",
      "ANKLE RIDE",
      "SPIRAL RIDE",
      "CLAW RIDE",
      "WRESTLING RIDES",
      "These riding controls can help maintain top position during turtle and scrambling exchanges."
    ],
    [
      "BARATOPLATA",
      "MONOPLATA",
      "OMOPLATA",
      "KIMURA",
      "SHOULDER-LOCK FAMILIES",
      "Each name describes a submission centered on controlling and rotating the shoulder."
    ]
  ],
  [
    [
      "SINGLE LEG X",
      "X-GUARD",
      "REVERSE X",
      "50/50",
      "LOWER-BODY GUARD CONFIGURATIONS",
      "These guards organize leg connections around the opponent's lower body."
    ],
    [
      "CROSS-WRIST GRIP",
      "TWO-ON-ONE",
      "ARM DRAG",
      "RUSSIAN TIE",
      "ARM ISOLATION CONTROLS",
      "These grips and movements focus control on one arm to create an angle."
    ],
    [
      "S-MOUNT",
      "TECHNICAL MOUNT",
      "HIGH MOUNT",
      "LOW MOUNT",
      "MOUNT CONFIGURATIONS",
      "These variations change hip and leg placement while remaining in the mount family."
    ],
    [
      "TOMOE NAGE",
      "SUMI GAESHI",
      "YOKO TOMOE",
      "LATERAL DROP",
      "SACRIFICE THROW OPTIONS",
      "These throws involve committing the attacker's own body toward the mat to complete the throw."
    ]
  ],
  [
    [
      "SEATBELT",
      "BODY TRIANGLE",
      "STRAIGHTJACKET",
      "DOUBLE HOOKS",
      "BACK CONTROL CONFIGURATIONS",
      "These are recognizable ways to organize control once behind an opponent."
    ],
    [
      "BOLO",
      "CRAB HOOKS",
      "LEG WEAVE",
      "HIP LIFT",
      "BERIMBOLO EXCHANGE VOCABULARY",
      "These terms describe inversion, hooking, leg control and elevation in berimbolo exchanges."
    ],
    [
      "BASEBALL CHOKE",
      "LOOP CHOKE",
      "CLOCK CHOKE",
      "BOW-AND-ARROW",
      "SPECIALIZED GI CHOKES",
      "These named finishes depend on collar or lapel control."
    ],
    [
      "KNEE SHIELD",
      "Z-GUARD",
      "LOCKDOWN",
      "DEEP HALF",
      "HALF GUARD VARIATIONS",
      "Each is a configuration of half guard rather than a separate top pin."
    ]
  ],
  [
    [
      "KNEE CUT",
      "SMASH PASS",
      "HEADQUARTERS",
      "HIP SWITCH",
      "HEADQUARTERS PASSING VOCABULARY",
      "These terms connect a central passing position to pressure, angle changes and passing options."
    ],
    [
      "BUTTERFLY SWEEP",
      "X-GUARD SWEEP",
      "DEEP HALF SWEEP",
      "LASSO SWEEP",
      "SWEEPS NAMED FOR THEIR GUARD",
      "Each sweep name identifies the guard configuration used to begin the reversal."
    ],
    [
      "INSIDE SANKAKU",
      "OUTSIDE ASHI",
      "CROSS ASHI",
      "ASHI GARAMI",
      "LEG ENTANGLEMENT FAMILIES",
      "These names describe specialized arrangements for controlling an opponent's leg."
    ],
    [
      "ELBOW ESCAPE",
      "BRIDGE AND ROLL",
      "KIPPING ESCAPE",
      "HEEL DRAG ESCAPE",
      "MOUNT ESCAPE OPTIONS",
      "These are different ways to recover space or reverse position from beneath mount."
    ]
  ],
  [
    [
      "LEG LASSO",
      "SPIDER GUARD",
      "COLLAR-SLEEVE",
      "DE LA RIVA",
      "GI OPEN GUARD CONTROLS",
      "These open guards commonly use sleeve, collar or pants grips to manage distance."
    ],
    [
      "SNAP DOWN",
      "GO BEHIND",
      "FRONT HEADLOCK",
      "SPIN BEHIND",
      "FRONT HEADLOCK TRANSITIONS",
      "These controls and movements connect a standing or turtle exchange to the front headlock and back."
    ],
    [
      "TOEHOLD",
      "KNEEBAR",
      "STRAIGHT ANKLE LOCK",
      "ESTIMA LOCK",
      "NAMED LOWER-BODY SUBMISSIONS",
      "These are named submissions directed at the leg or foot."
    ],
    [
      "BICEPS FRAME",
      "HIP FRAME",
      "NECK FRAME",
      "SHOULDER FRAME",
      "FRAME CONTACT POINTS",
      "Each names a body area where a frame can help manage pressure and space."
    ]
  ],
  [
    [
      "SLEEVE DRAG",
      "COLLAR DRAG",
      "LAPEL DRAG",
      "ARM DRAG",
      "DRAG ENTRIES",
      "These entries draw the opponent past a control point to expose an angle."
    ],
    [
      "LEG STAPLE",
      "SHIN PIN",
      "KNEE PIN",
      "ANKLE PIN",
      "LOWER-BODY PASSING PINS",
      "These controls restrict a leg or part of the leg during guard passing."
    ],
    [
      "CRUCIFIX",
      "TRUCK",
      "TURTLE",
      "BACK MOUNT",
      "REAR CONTROL POSITIONS",
      "These are distinct positions encountered while controlling an opponent from behind or beside the back."
    ],
    [
      "WAITER SWEEP",
      "MERMAID SWEEP",
      "BALLOON SWEEP",
      "SICKLE SWEEP",
      "OPEN GUARD SWEEP VARIATIONS",
      "These named sweeps use different lower-body connections and directions to reverse position."
    ]
  ],
  [
    [
      "WHIZZER",
      "UNDERHOOK CLINCH",
      "DOUBLE UNDERHOOKS",
      "OVER-UNDER CLINCH",
      "CLINCH ARM CONFIGURATIONS",
      "These names describe how the arms connect around an opponent in a clinch."
    ],
    [
      "GRANBY ROLL",
      "SIT OUT",
      "SWITCH",
      "PEEK OUT",
      "TURTLE ESCAPE MOVEMENTS",
      "These movements create angles to leave turtle or reverse a riding exchange."
    ],
    [
      "LAPEL WRAP",
      "SLEEVE TENSION",
      "COLLAR ANCHOR",
      "PANTS ANCHOR",
      "GI CONTROL CONCEPTS",
      "These describe how fabric grips maintain a connection and limit movement."
    ],
    [
      "FAR HIP",
      "NEAR HIP",
      "BELT LINE",
      "BACK OF KNEE",
      "CRAB RIDE CONTROL LANDMARKS",
      "These landmarks help describe the grip and hook connections in a crab ride."
    ]
  ],
  [
    [
      "ARM-IN GUILLOTINE",
      "HIGH-ELBOW GUILLOTINE",
      "MARCELOTINE",
      "TEN-FINGER GUILLOTINE",
      "GUILLOTINE VARIATIONS",
      "These names refer to distinct grip or arm configurations within the guillotine family."
    ],
    [
      "SCOOP GRIP",
      "HEEL CUP",
      "TOE LINE",
      "ACHILLES GRIP",
      "FOOT AND LEG GRIP VOCABULARY",
      "These terms identify grips and landmarks used to describe lower-body control."
    ],
    [
      "REVERSE HALF",
      "DOGFIGHT",
      "OCTOPUS GUARD",
      "COYOTE HALF",
      "HALF GUARD TRANSITION SYSTEMS",
      "These positions connect half guard to angled upper-body control and coming up."
    ],
    [
      "KNEE SLICE RECOVERY",
      "LEG DRAG RECOVERY",
      "STACK RECOVERY",
      "BODY LOCK RECOVERY",
      "RETENTION BY PASSING THREAT",
      "Each names a guard recovery problem according to the pass being addressed."
    ]
  ],
  [
    [
      "SINGLE LEG FINISH",
      "DOUBLE LEG FINISH",
      "ANKLE PICK FINISH",
      "KNEE TAP FINISH",
      "STANDING FINISH FAMILIES",
      "Each names a takedown finish according to its primary lower-body target."
    ],
    [
      "INSIDE POSITION",
      "KNEE-ELBOW CONNECTION",
      "HIP MOBILITY",
      "DISTANCE MANAGEMENT",
      "GUARD RETENTION PRINCIPLES",
      "These principles organize defensive movement before a guard pass is completed."
    ],
    [
      "WRIST TRAP",
      "ELBOW CONTROL",
      "ARM PIN",
      "HAND FIGHT",
      "BACK ATTACK ARM MANAGEMENT",
      "These controls address the defending arms during a back-control exchange."
    ],
    [
      "LAPEL GUARD",
      "WORM LAPEL",
      "SQUID LAPEL",
      "LASSO LAPEL",
      "LAPEL CONTROL VOCABULARY",
      "These terms identify lapel-based guard and wrapping connections."
    ]
  ],
  [
    [
      "CHAIR SIT ENTRY",
      "ROLLING ENTRY",
      "ARM DRAG ENTRY",
      "CRAB RIDE ENTRY",
      "BACK TAKE ENTRY FAMILIES",
      "Each names a route into a back take according to its starting movement or control."
    ],
    [
      "LONG STEP COUNTER",
      "KNEE CUT COUNTER",
      "TORIANDO COUNTER",
      "LEG DRAG COUNTER",
      "PASS-SPECIFIC COUNTERS",
      "Each is a defensive problem named for the passing action being countered."
    ],
    [
      "SADDLE",
      "80/20",
      "OUTSIDE ASHI GARAMI",
      "50/50 ENTANGLEMENT",
      "ADVANCED LEG POSITION VOCABULARY",
      "These terms identify specialized leg-control configurations."
    ],
    [
      "OMOPLATA SWEEP",
      "TRIANGLE TO ARMBAR",
      "KIMURA TO BACK",
      "GUILLOTINE TO SWEEP",
      "ATTACK-TO-TRANSITION CONNECTIONS",
      "These pair an initial submission threat with another attack or a positional transition."
    ]
  ]
];
const PUZZLES = [...DAILY_PUZZLES, ...BROWN_ROUNDS.map((groups, index) => ({
  id: 101 + index, difficulty: "brown",
  groups: groups.map(g => ({items:g.slice(0,4), category:g[4], explanation:g[5]}))
}))];

function validatePuzzle(puzzle) {
  const items = puzzle.groups.flatMap(g => g.items);
  const errors = [];
  if (puzzle.groups.length !== 4) errors.push("Puzzle must have 4 groups.");
  if (items.length !== 16) errors.push("Puzzle must have 16 items.");
  if (new Set(items).size !== items.length) errors.push("Puzzle contains duplicate items.");
  puzzle.groups.forEach((g,i) => {
    if (g.items.length !== 4) errors.push(`Group ${i+1} must have 4 items.`);
    if (!g.category) errors.push(`Group ${i+1} is missing a category.`);
    if (!g.explanation) errors.push(`Group ${i+1} is missing an explanation.`);
  });
  return errors;
}

// Bank-level check: catches an exact-duplicate puzzle (same 4 category
// names + same 16 words as another puzzle) before it ships. This is the
// check that would have caught puzzles #28/#40 being identical.
function validateAllPuzzles(puzzles) {
  const errors = [];
  puzzles.forEach(p => errors.push(...validatePuzzle(p).map(e => `Puzzle ${p.id}: ${e}`)));
  const seen = new Map();
  const seenWords = new Map();
  const groupCounts = new Map();
  puzzles.forEach(p => {
    const key = JSON.stringify(p.groups.map(g => ({ c: g.category, i: g.items.slice().sort() }))
      .sort((a, b) => a.c.localeCompare(b.c)));
    if (seen.has(key)) errors.push(`Puzzle ${p.id} is an exact duplicate of puzzle ${seen.get(key)}.`);
    else seen.set(key, p.id);
    p.groups.forEach(g => {
      const groupKey = JSON.stringify(g.items.slice().sort());
      const count = (groupCounts.get(groupKey) || 0) + 1;
      groupCounts.set(groupKey, count);
      if (count > 3) errors.push(`Puzzle ${p.id}: four-word group appears ${count} times (maximum 3).`);
    });
    const wordsKey = JSON.stringify(p.groups.flatMap(g => g.items).slice().sort());
    if (seenWords.has(wordsKey)) errors.push(`Puzzle ${p.id} repeats all 16 words from puzzle ${seenWords.get(wordsKey)}.`);
    else seenWords.set(wordsKey, p.id);
  });
  return errors;
}
