const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const html=fs.readFileSync('resources.html','utf8');
const glossary=html.match(/var GLOSSARY = \[[\s\S]*?\n\];/)[0];
const c={};vm.createContext(c);
for(const file of ['techniques.js','technique-videos.js','glossary-videos.js','resource-catalog.js'])vm.runInContext(fs.readFileSync(file,'utf8'),c);
vm.runInContext(glossary+';globalThis.techniques=TECHNIQUES;globalThis.videos=TECHNIQUE_VIDEOS;globalThis.entries=BJJResources.build(TECHNIQUES,GLOSSARY,TECHNIQUE_VIDEOS,GLOSSARY_VIDEOS)',c);
assert(c.techniques.length>=185);
assert.equal(c.entries.filter(e=>e.technique).length,c.techniques.length);
assert.equal(new Set(c.entries.map(e=>e.term)).size,c.entries.length);
for(const t of c.techniques) {
 const entry=c.entries.find(e=>e.term===t.name);
 assert(entry,`${t.name} must appear in Resources`);
 assert.equal(entry.def,t.desc);
 assert(entry.category && entry.def.length>20);
 assert.match(entry.video?.url||'',/^https:\/\/www.youtube.com\/watch\?v=[\w-]{11}$/,
  `${t.name} requires a direct video URL, not a search page`);
 assert(entry.video.title.length>3);
 assert(c.BJJResources.matches(entry,t.name));
 const card=c.BJJResources.card(entry);
 assert(card.includes('Watch video ↗'));
 assert(card.includes(entry.video.url));
 assert(card.includes('rel="noopener noreferrer"'));
}
assert.equal(c.entries.length,284);
assert.equal(new Set(c.entries.map(e=>e.video.url)).size,284,'Each entry has a distinct video');
for(const entry of c.entries) {
 assert(entry.def.length>20,entry.term+' needs a description');
 assert.match(entry.video?.url||'',/^https:\/\/www.youtube.com\/watch\?v=[\w-]{11}$/,entry.term+' needs a direct video');
 assert(entry.video.title.length>3,entry.term+' needs a video title');
}
assert(fs.readFileSync('sw.js','utf8').includes('"/glossary-videos.js"'));
const baseball=c.entries.find(e=>e.term==='Baseball Bat Choke');
assert(c.BJJResources.matches(baseball,'baseball choke'));
assert(c.BJJResources.matches(baseball,'baseball bat choke'));
assert.equal(c.entries.filter(e=>e.term==='Side Control').length,1);
assert(c.entries.some(e=>e.term==='OSS'),'preserve non-technique glossary content');
assert(!c.BJJResources.matches(baseball,'no-such-technique'));
const escaped=c.BJJResources.card({...baseball,term:'<script>',def:'a & b',video:{...baseball.video,title:'<iframe>'}});
assert(!escaped.includes('<script>') && !escaped.includes('<iframe>'));
const nodes=new Map();
function node(){return {value:'',innerHTML:'',textContent:'',events:{},children:[],appendChild(el){this.children.push(el);},focus(){},classList:{add(){},remove(){}},addEventListener(k,f){this.events[k]=f;}};}
for(const id of ['glossarySearch','noGlossaryResults','glossaryCount','glossarySections','glossaryCategory','pickLesson','clearGlossaryFilters'])nodes.set(id,node());
nodes.get('glossaryCategory').value='all';
c.document={getElementById:id=>nodes.get(id),createElement:()=>node()};
c.window={open:(...args)=>{c.opened=args;}};c.location={search:'?q=Baseball%20Bat%20Choke'};c.URLSearchParams=URLSearchParams;
const renderScript=html.match(/\(function\(\) \{\n  var entries = BJJResources[\s\S]*?\}\)\(\);/)[0];
vm.runInContext(renderScript,c);
assert.equal(nodes.get('glossarySearch').value,'Baseball Bat Choke');
assert.match(nodes.get('glossaryCount').textContent,/1 entry · 1 video/);
assert(nodes.get('glossarySections').innerHTML.includes(baseball.video.url));
nodes.get('glossarySearch').value='';nodes.get('glossarySearch').events.input();
assert.equal((nodes.get('glossarySections').innerHTML.match(/class="resource-watch"/g)||[]).length,c.entries.length);
assert.equal(nodes.get('glossaryCount').textContent,'284 entries · 284 videos');
assert.equal(nodes.get('glossaryCategory').children.length,14);
nodes.get('glossaryCategory').value='Submissions';nodes.get('glossaryCategory').events.change();
assert(nodes.get('glossarySections').innerHTML.includes('Baseball Bat Choke'));
assert(!nodes.get('glossarySections').innerHTML.includes('<dt>Base</dt>'));
assert.equal(nodes.get('pickLesson').disabled,false);
nodes.get('glossarySearch').value='Baseball Bat Choke';nodes.get('glossarySearch').events.input();
nodes.get('pickLesson').events.click();
assert.equal(c.opened[0],baseball.video.url);
assert.equal(c.opened[2],'noopener,noreferrer');
nodes.get('clearGlossaryFilters').events.click();
assert.equal(nodes.get('glossaryCount').textContent,'284 entries · 284 videos');
assert.equal(nodes.get('clearGlossaryFilters').hidden,true);
nodes.get('glossarySearch').value='crab ride';nodes.get('glossarySearch').events.input();
assert(nodes.get('glossarySections').innerHTML.includes('Crab Ride Back Take'));
assert(!nodes.get('glossarySections').innerHTML.includes('Baseball Bat Choke'));
nodes.get('glossarySearch').value='no-such-technique';nodes.get('glossarySearch').events.input();
assert.equal(nodes.get('glossarySections').innerHTML,'');
assert.equal(nodes.get('pickLesson').disabled,true);
assert(fs.readFileSync('sw.js','utf8').includes('"/technique-videos.js"'));
assert(fs.readFileSync('sw.js','utf8').includes('"/resource-catalog.js"'));
console.log(`Resources coverage passed: ${c.techniques.length} techniques, descriptions and direct video links; ${c.entries.length} total entries. Alias search, grouping, deep links and safe rendering passed.`);
