const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const context = {window:{}, document:{getElementById:()=>null}};
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(__dirname,'../round-timer.js'),'utf8'),context);
let time = 0;
const timer = context.window.BJJRoundClock({workSeconds:120,restSeconds:30,rounds:3},()=>time);
assert.equal(timer.snapshot().seconds,120);
timer.start(); time = 125000;
assert.equal(timer.snapshot().label,'Rest');
assert.equal(timer.snapshot().seconds,25,'a delayed callback enters the rest phase at the correct remaining time');
timer.pause(); time += 900000;
assert.equal(timer.snapshot().seconds,25,'paused time does not elapse');
timer.start(); time += 25000;
assert.equal(timer.snapshot().label,'Work');
assert.equal(timer.snapshot().round,2);
assert.equal(timer.snapshot().seconds,120);
time += 400000;
assert.equal(timer.snapshot().finished,true,'a backgrounded timer can cross multiple phases and finish');
assert.equal(timer.snapshot().seconds,0);
assert.equal(timer.snapshot().running,false);
timer.start(); assert.equal(timer.snapshot().finished,true);
time = 0;
const noRest = context.window.BJJRoundClock({workSeconds:60,restSeconds:0,rounds:2},()=>time);
noRest.start();time=60000;
assert.equal(noRest.snapshot().label,'Work');
assert.equal(noRest.snapshot().round,2);
time=120000;
assert.equal(noRest.snapshot().finished,true,'there is no extra rest after the final round');
console.log('Round timer pause/resume, background elapsed time, phase transitions, and completion passed.');
